### ISSUE TITLE
Running monstache in container with workers

### ISSUE THREAD

**Issue by sameerkattel** [rwynn/monstache#121]
How one should configure docker-compose.yml file to run multiple workers in a docker container?

Here is my docker-compose.yml

`version: '3'
services:
 monstache:
    container_name: monstache
    restart: always
    image: rwynn/monstache:4.11.1
    command: -f /app/monstache/config.toml
    volumes:
        - /home/ubuntu/elasticsearch/monstache:/app/monstache
`

**Comment by rwynn** [comment]
You need a separate process for each worker. So maybe N services each with a different -worker argument in the command?

**Comment by sameerkattel** [comment]
Should not all the worker run inside a same container?

**Comment by rwynn** [comment]
Monstache does not do any forking so I think you would need multiple services.  They can all use the same Monstache container. 

Or don’t use workers at all since they may not be necessary. Monstache uses many goroutines so you may not need multiple process.

**Comment by gabrielmcf** [comment]
Using monstache in kubernetes, if I create a deployment with multiple containers, each one running one worker, how do they communicate? Through localhost? Or they must be inside the same container?

**Comment by rwynn** [comment]
The workers options is about dividing up the work of indexing.  It works in a simple way but you need to commit to the number of workers up front (cannot add and remove workers on the fly).  Each config file needs 
to declare the names of **all** the workers: W1, W2, etc.  Then you need to start N processes where N is the number of workers in the config files.  Each process is given one of the worker names via `-worker W1`.    

They then don't need to communicate because they have the names of all the workers.  They `all read the data` but only one worker will index it.  The load balancing part is on the indexing side.  They can be in different containers.  They work like nginx [ip-hash](http://nginx.org/en/docs/http/load_balancing.html) load balancing, but just to determine which will send the data to Elasticsearch.    

Workers are not for high availability though.  For HA you would want the `cluster-name` option.  The processes communicate through MongoDB.  They don't need to be in the same container.  Processes in the same cluster coordinate so that one is running and the others are paused.

**Comment by gabrielmcf** [comment]
Thank you for your answer! And thank you for the great piece of software!
