### ISSUE TITLE
How to do automatic re-indexing when child/embed doc updated

### ISSUE THREAD

**Issue by m3hari** [rwynn/monstache#125]
Hello, Thank you're very much for the awesome job you are doing.

We tried different approaches and/or tools to sync MongoDB and Elastic search, Monstache is the best one we found.

After some researching on methodologies of handling relational data on Elasticsearch (app side join, denormalizing, nested object,parent-child), We decided **denormalizing** is the best way to go for our case.

We have successfully indexed our database(denormalized), using Monstache middleware feature.
Here is our javascript plugin 

```javascript 
module.exports = function(employee) {
  if (!!employee.deletedAt) {
    return false;
  }
  if (employee.companyId) {
    var company = findId(employee.companyId, {
      database: "app-db",
      collection: "Company"
    });
    employee.company = company;
  }
  return employee;
};
```

As you know the **issue with denormalizing approach is we have to re-index the parent docs** (in our case employee) **when children/embeded docs got updated/deleted** (in our case when company got updated)

**What is the way to handle this in monstache?**

**Comment by m3hari** [comment]
@rwynn you have mentioned related topic on another issue here #86 

> Also once you embed an object from another collection, the only way to keep in sync using monstache would be to reindex by restarting direct reads so that the country is updated by fetching it again in the script phase.

But I don't clearly understand what you mean by ` reindex by restarting direct reads`

**Comment by rwynn** [comment]
You can try the new [relate] feature to accomplish the sync of parent when child changes. 

See ‘MongoDB view replication’ topic at https://rwynn.github.io/monstache-site/advanced/.  

You would need to create a relationship such that when company changes then all employees with that company id are resynced.

**Comment by rwynn** [comment]
What I meant by re-index was that if you configure monstache to do direct-reads of the employee collection then by restarting Monstache you will force a reread and sync of all documents. This would pick up any changes to the company by re-executing the script for each doc. But since this is not an optimal solution the [relate] config was added to solve it. 

Another solution that you may want to investigate is using a mongodb view instead of a script to do the lookup before indexing. This is explained in the last section of the advanced page. This may be more performant than using a script to lookup.

**Comment by m3hari** [comment]
Thank you very much for the thorough explanation. I will take a look into mongodb views.

**Comment by m3hari** [comment]
The **_relate_** feature works for me. Thanks.
