### ISSUE TITLE
 ERROR 2018/11/13 11:24:59 Error reading segment of collection test.pictures. Will retry segment.: cursor id 71467632819 not found

### ISSUE THREAD

**Issue by thomasd3** [rwynn/monstache#130]
Hi,
I have a series of lines like this:

ERROR 2018/11/13 11:24:59 Error reading segment of collection test.pictures. Will retry segment.: cursor id 71467632819 not found

what does it mean? 

I inserted about 120k recording in MongoDB and Monstache build ~40k records in ES.

**Comment by rwynn** [comment]
Maybe Elasticsearch is not keeping up with the indexing and Mongodb cursor is timing out by the server.  Do you have custom settings?

**Comment by rwynn** [comment]
It will retry that segment as indicated in the message.  A segment is just a range of docs within a collection. The source for this is in rwynn/gtm gtm.go. Check the function DirectReadSegment.  It calls itself again on error. 

Usually what happens is Mongo is fast to read but Elasticsearch is slow to index. I’ve seen up to 1 million docs synced through per minute in testing.  It doesn’t seem like you are seeing close to that.

**Comment by rwynn** [comment]
Turn on stats so that you can see the progress.

**Comment by rwynn** [comment]
Specifically, this error is coming from this line of code:

https://github.com/rwynn/gtm/blob/master/gtm.go#L1120

I'm not sure why it would have an error at that point.  I've seen something like this when MongoDB was restarted or a very large collection is read.  But 120k documents is not large.

Gtm is writing these documents from MongoDB on a buffered channel.  In order for that channel write not to block, the reading end, in this case Monstache reading and bulking to Elasticsearch, must happen quickly.  If Elasticsearch is taking a long time to process a bulk request, then Gtm cannot write to this channel.  In that case it's possible that MongoDB doesn't see a read on the cursor for a long enough time and kills it. 

https://docs.mongodb.com/manual/reference/method/cursor.maxTimeMS/

There are a couple things you can do.  You can increase the buffer size of the channel that gtm uses so that the writes to the channel do not block.  This will cause monstache to use more memory to buffer these docs.

```
[gtm-settings]
channel-size = 50000
```

Or, better yet would be to figure out why monstache is not able to commit bulk requests to Elasticsearch fast enough.  If you are using a script, is the script exiting quickly?  You can use console.log() in a script and monstache will output it to standard out.

**Comment by rwynn** [comment]
Another approach that would help clear the channel buffer would be to set the `elasticsearch-max-bytes` to a lower value (defaults to 8mb in bytes).  This will cause monstache to flush more frequently in smaller batch sizes.  That may help.  E.g. 800k instead of 8mb.  Also reduce the connections from 4 to 2.  

```
elasticsearch-max-bytes = 800000
elasticsearch-max-conns = 2
```

If your version of Elasticsearch is older than 6 then I would also look into increasing the bulk threadpool queue size:

https://rwynn.github.io/monstache-site/config/#elasticsearch-max-conns

**Comment by thomasd3** [comment]
Let me try these and I'll report here

**Comment by thomasd3** [comment]
Errors are gone, however sync has become very slow; it took several hours to do the 120k records and since it's pictures, most have 5-6 words max as tags

**Comment by rwynn** [comment]
Yeah that sounds like something is not quite right here.  I usually see just under 1 million records per minute (testing sync on a 22 million doc collection) in a VM with MongoDB and Elasticsearch installed together.  So the whole 22 million docs take about 23-24 minutes.  Not lining up at all with your results.

**Comment by thomasd3** [comment]
I have ES6 + Mongo 4 straight from their docker image, no customization. I use a Mac for development and the stuff runs on CentOS in production. I have a slow speed on both, so it's not some esoteric setting.
I will try to give ES more memory to see what happens. The docker compose has this for now:

     environment:
       - cluster.name=docker-cluster
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     ulimits:
       memlock:
         soft: -1
         hard: -1

**Comment by rwynn** [comment]
You might want to try configuring the Elasticsearch slow log for indexing to get more information 

https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html

**Comment by rwynn** [comment]
This is link shows how to enable the slow log

https://qbox.io/blog/slow-logs-in-elasticsearch-search-index-config-example

**Comment by rwynn** [comment]
If you enable stats then you can see how long bulk operations are taking to index. 

```
stats = true
```
The duration of the last bulk index to Elasticsearch will be printed in a field named `LastDuration`.  Unfortunately, to get the ms you would need to divide this nano second value by 1,000,000.

**Comment by thomasd3** [comment]
I will do some extra logging and report.

**Comment by thomasd3** [comment]
I close this one since we fixed a major problem on the other thread; maybe this issue will not pop up again.
