### ISSUE TITLE
How to change _id to prevent duplicates when sending data from multiple collections into 1 ES index

### ISSUE THREAD

**Issue by nakulm95** [rwynn/monstache#151]
In my situation, I'm tailing 1 Mongodb collection at the moment and dumping that data into 1 ES index, so chances of duplicates are low to none. As I start tailing other collections and dumping their data into the same index, chances of duplicate _id values increase quite a bit. So, in my Map function, I am creating a custom _id value which is a concatenation of the original mongo _id and a string which represents the type of the document being added (to prevent duplication), but the _id created in the output document is deleted before being sent to ES.

So, is there any way to supply a custom _id for the output document?

Thanks!

**Comment by nakulm95** [comment]
Hey Ryan,

Any ideas on this one, besides splitting the data into multiple indices?

Thanks!

**Comment by rwynn** [comment]
Hi @nakulm95, monstache have always defaulted to index per collection for this reason of colliding IDs with the assumption that if you need to query across MongoDB collections then you would use a wildcard `index-pattern` in your Elasticsearch query such as `db.*` instead of referencing a single index.  

I will add the ability to override the ID in the next version.  The problem will be that delete will not work without adding addition scripting to monstache since the map phase is only run for creates and updates and not deletes.  If you also need delete to work then I would suggest multiple indexes (one per collection).  

The other option is to implement a go plugin and implement the `Process` function that gives you control over the indexing.  Obviously this requires a bit more work.

**Comment by rwynn** [comment]
@nakulm95 the very latest version of monstache now lets you override the _id sent to Elasticsearch.  You can do something like this now:

```
[[script]]
namespace = "db.col"
script = """
module.exports = function(doc) {
    var meta = { id: "my-custom-id" };
    doc._meta_monstache = meta;
    return doc;
}
"""
```

All the things you can set on this meta object are defined here:

https://rwynn.github.io/monstache-site/advanced/#indexing-metadata

**Comment by rwynn** [comment]
When you implement `Process` you need to do the indexing yourself.  This is not too hard since the bulkIndexer and elasticClient are passed into your function.  Take a look at the monstache code to see how it calls `Add` on the bulk processor to add an item to the bulk request.  

As far as stats are concerned.  If you have stats on then you will get stats for anything that gets sent to the bulk processor including stuff your `Add` yourself in a `Process` function.

**Comment by nakulm95** [comment]
Thanks for making the _id change! Is it possible to make the changes to _id through the functions (Map, Process, etc.) directly, rather than using JS in the config file?

**Comment by nakulm95** [comment]
also wanted to swing another question by you. how does Process relate to Map? Reading through the code, a document goes through both if both are provided, so I'm not sure what sure how they fit together.

**Comment by rwynn** [comment]
@nakulm95 

These function evolved over time.  `Map` was added first.  From a `Map` function you have access to the document that changed and to the MongoDB client.  A `Map` function is 1:1 in that it takes in a document and can only return 1 document to be indexed. 

 `Process` was added later to handle more complex scenarios.  `Process` does not return anything.  It gets access to the MongoDB client, Elasticsearch client, and a bulkProcessor.  In the `Process` function you can have all sorts of side effects but you in control of the indexing and would need to either use the Elasticsearch client and/or bulk processor passed in.  For an example of what you ultimately want to do inside a `Process` function see [doIndexing](https://github.com/rwynn/monstache/blob/v4.13.0/monstache.go#L2516)

The input/output to these functions is [here](https://github.com/rwynn/monstache/blob/v4.13.0/monstachemap/plugin.go)

**Comment by rwynn** [comment]
@nakulm95 to answer previous question, yes it is no possible to override the _id in `Map` function now using the new field on [MapperPluginOutput](https://github.com/rwynn/monstache/blob/v4.13.0/monstachemap/plugin.go#L30).  For `Process` it has always been possible since in that case you are responsible for doing the indexing.  You can use whatever _id that you would like there.

**Comment by nakulm95** [comment]
Thanks for the information Ryan! Given what Map and Process do, do they tie in together if both are implemented? I.e. the output from Map will be passed in to Process? If I index the document read from Mongo in Process, then what happens to the document returned from Map? Since Map is a required function, while Process isn't, I'm trying to understand how the 2 interact with each other (if at all).

If Process can do everything, then what is Map for?

**Comment by rwynn** [comment]
`Map` is no longer a required function in the latest version.  I think I added it to the release notes but didn't completely update the docs.  

The output of `Map` is actually not fed into `Process`.  

You can think of it this way, if you simply need to make minor modifications to the data and you only need access to a MongoDB client (e.g. to lookup something and possibly add it to the result) then use `Map`.  `Map` can only index 1 thing - a 1 to 1 transform.  

If you need to do more complex stuff with side effects then use `Process`.  In `Process` have access to MongoDB and Elasticsearch clients.  You could "map" one event to multiple indexing instructions in `Process`.  You can perform deletes in `Process`.  There is no output for this function.  It is a generic event handler that you can perform multiple side effects in.  

If you want to do everything yourself in Process then you can basically turn off the automatic features by implementing a `Map` function that always returns `Skip=true` and then also set `delete-strategy` to `2` and `dropped-collections` and `dropped-databases` to `false`.   You are correct that these automatic things still happen when you implement `Process`.    

In retrospect it may have been better to only support a `Process` function.  But these things were added over time and try to maintain backwards compat.  It is sometimes nice to use `Map` for certain simple use cases since that only involves converting data from one form to another and leaves the indexing step to Monstache.

**Comment by nakulm95** [comment]
That adds a lot of clarity to how things are behaving, thank you!

Few more questions:
1) In mapData, if a Map function is not provided then mapDataJavascript is called. What if neither are provided? What is the expected behavior?
2) > You are correct that these automatic things still happen when you implement Process. 
Does this mean for invalid operations ("c") we can assume monstache will take care of it? or do we lose any guarantees? I'm leaning towards a mixed approach since I don't have access to a few things in Process that are available in the monstache world to make life easier.

**Comment by rwynn** [comment]
> In mapData, if a Map function is not provided then mapDataJavascript is called. What if neither are provided? What is the expected behavior?

It will simply do a noop in `mapDataJavascript` if no scripts are configured for the op namespace or global namespace.  This just means that the MongoDB data passes through unmodified.


> Does this mean for invalid operations ("c") we can assume monstache will take care of it? or do we lose any guarantees? I'm leaning towards a mixed approach since I don't have access to a few things in Process that are available in the monstache world to make life easier.

In some cases you can mix and match and in others you cannot.  For example, you can check the namespace of the event in `Map` and return `Skip=true` for some events and then process them in `Process`.  For the events that you don't skip then monstache will just index as usual and obviously you should ignore them in `Process`.  For deletes and drops you can either turn then on or off.  If you turn them off then you need to handle them all yourself in `Process`.

**Comment by nakulm95** [comment]
Thanks! Closing this b/c I have plenty to go off of now.

**Comment by batamar** [comment]
Hi @nakulm95 Did you find the solution?

**Comment by batamar** [comment]
Hi @rwynn . It looks like quite an old issue. Maybe there is a solution in monstache now?
