### ISSUE TITLE
how to delta sync data from mongo to elasticsearch after first time full sync data?

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/monstache#152]
hi Ryan,

    i want to know the delta sync data setting from mongodb to elasticsearch according to timestamp using this service, how to set in configuration file or other method? thanks

**Comment by rwynn** [comment]
If I understand you correctly you can use the following in your config file

```
resume = true
resume-from-timestamp = 1234....
```

Where `resume-from-timestamp` value is a 64 bit integer that you can copy from the oplog collection `ts` field.  Syncing will resume for all events after this timestamp.  

The first 32 bits of the timestamp are seconds since the epoch, so you could calculate the timestamp value by shifting epoch seconds left 32 bits.  It doesn't have to necessarily exist in the oplog but it can.  

https://docs.mongodb.com/manual/reference/bson-types/#timestamps

Finally, you cannot use `change-stream-namespaces` with resume.  Resuming currently only works for the monstache mode where it tails the oplog directly.  Hopefully, when the MongoDB driver supports resuming change streams from a timestamp I will add that capability.  I have a PR with the driver to add that support but it has not been merged yet. 

https://github.com/globalsign/mgo/pull/306

**Comment by rwynn** [comment]
If you run simply with `resume` = true and leave out `resume-from-timestamp` then monstache will first check its own metadata collection in MongoDB to see if a timestamp was saved from a previous run.  If the timestamp is found it will resume from that timestamp.  

The collection is `monstache.monstache` by default.  This collection is where monstache tracks progress.  There will be a document in that collection with a `ts` field.  Monstache will write to this collection as it progresses (after each user operation) when `resume` = true. 

Alternatively, if you have a timestamp created by your application then you can use it to replace the `ts` field in `monstache.monstache` and that value will be used to resume from when `resume` = true.

`resume-from-timestamp` is an option that lets you manually override the timestamp that you resume from instead of monstache reading it from the `monstache.monstache` collection.  

Does that answer your question?

**Comment by sunweiconfidence** [comment]
ok, if i have the createdate field in collection, then i can define it in  resume-from-timestamp=createdate to dynamically get latest timestamp, am i right?

**Comment by rwynn** [comment]
no, that would not work cause `resume-from-timestamp` is an int64 not a field name.  It must be a timestamp as you would find in the MongoDB [oplog](https://docs.mongodb.com/manual/core/replica-set-oplog/).  

You shouldn't need to mess with `resume-from-timestamp` generally.  Just run with `resume=true` always.  After you finish your full sync then run afterwards without `direct-read-namespaces` to skip the full copy.

**Comment by sunweiconfidence** [comment]
ok, thanks Ryan, i know it now.

**Comment by abhijitbashetti** [comment]
Hi Ryan,

I have the same issue. The full sync happens fine. But the later on if I add any more data to MOngoDB then its not been updated to ElasticSearch.

Here is my config : 

# connection settings

mongo-url = "mongodb://mongo:mongo@localhost:27017"
elasticsearch-urls = ["http://localhost:9200"]

direct-read-namespaces = [ "test.test" ]
#change-stream-namespaces = [ "test.test" ]
# Oplog read operation timeout setting.
#[mongo-dial-settings]
timeout=15
read-timeout=7
write-timeout=7

#[mongo-session-settings]
socket-timeout=7
sync-timeout=7

#[logs]
info = "/monstache/logs/info.log"
warn = "/monstache/logs/warn.log"
error = "/monstache/logs/error.log"
trace = "/monstache/logs/trace.log"

# additional settings
gzip = true
stats = true
index-stats = true
mongo-validate-pem-file = false

elasticsearch-max-docs = 1
elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 800000 
index = "user"
type = "_doc"
dropped-collections = false
dropped-databases = false
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
index-files = false
file-highlighting = false
verbose = true
exit-after-direct-reads = true

index-as-update=true
index-oplog-time=true

Here is my log :


D:\15-1-19>monstache -f config.toml
WARN 2019/01/16 17:37:44 For performance reasons it is recommended to use elasticsearch-max-bytes instead of elasticsearch-max-docs since doc size may vary
INFO 2019/01/16 17:37:44 Started monstache version 4.13.0
INFO 2019/01/16 17:37:44 Successfully connected to MongoDB version 4.0.2
INFO 2019/01/16 17:37:44 Successfully connected to Elasticsearch version 6.5.3
INFO 2019/01/16 17:37:44 Sending systemd READY=1
WARN 2019/01/16 17:37:44 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2019/01/16 17:37:44 Listening for events
TRACE 2019/01/16 17:37:44 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 205
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c482415015dbb4fb576f2"}}
{"doc":{"age":29,"name":"ABhijit","oplog_date":"2019/01/16 12:07:44","oplog_ts":6647065178846265344},"doc_as_upsert":true}

TRACE 2019/01/16 17:37:44 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 203
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c484d15015dbb4fb576f5"}}
{"doc":{"age":30,"name":"Datta","oplog_date":"2019/01/16 12:07:44","oplog_ts":6647065178846265344},"doc_as_upsert":true}

TRACE 2019/01/16 17:37:44 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 204
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c483a15015dbb4fb576f4"}}
{"doc":{"age":27,"name":"Ganesh","oplog_date":"2019/01/16 12:07:44","oplog_ts":6647065178846265344},"doc_as_upsert":true}

TRACE 2019/01/16 17:37:44 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 202
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c482e15015dbb4fb576f3"}}
{"doc":{"age":29,"name":"Amol","oplog_date":"2019/01/16 12:07:44","oplog_ts":6647065178846265344},"doc_as_upsert":true}

TRACE 2019/01/16 17:37:44 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":151,"errors":false,"items":[{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c482e15015dbb4fb576f3","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:37:44 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 204
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c5b4615015dbb4fb576f6"}}
{"doc":{"age":30,"name":"Rajesh","oplog_date":"2019/01/16 12:07:44","oplog_ts":6647065178846265344},"doc_as_upsert":true}

TRACE 2019/01/16 17:37:44 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":162,"errors":false,"items":[{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c484d15015dbb4fb576f5","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:37:44 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":163,"errors":false,"items":[{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c483a15015dbb4fb576f4","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:37:44 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":11,"errors":false,"items":[{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c5b4615015dbb4fb576f6","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:37:45 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Warning: 299 Elasticsearch-6.5.3-159a78a "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Wed, 16 Jan 2019 12:07:44 GMT"

{"took":191,"errors":false,"items":[{"update":{"_index":"test.test","_type":"_doc","_id":"5c3c482415015dbb4fb576f2","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
ERROR 2019/01/16 17:37:45 299 Elasticsearch-6.5.3-159a78a "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Wed, 16 Jan 2019 12:07:44 GMT"
TRACE 2019/01/16 17:38:19 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 406
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc"}}
{"Host":"Abhijiitbw81","Pid":5424,"Stats":{"Flushed":6,"Committed":5,"Indexed":0,"Created":0,"Updated":5,"Deleted":0,"Succeeded":5,"Failed":0,"Workers":[{"Queued":0,"LastDuration":163000000},{"Queued":0,"LastDuration":162000000},{"Queued":0,"LastDuration":191000000},{"Queued":0,"LastDuration":11000000}]},"Timestamp":"2019-01-16T12:08:14"}

TRACE 2019/01/16 17:38:20 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Warning: 299 Elasticsearch-6.5.3-159a78a "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Wed, 16 Jan 2019 12:08:19 GMT"

{"took":230,"errors":false,"items":[{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc","_id":"DSqPVmgBN2iqLKf875ko","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
ERROR 2019/01/16 17:38:20 299 Elasticsearch-6.5.3-159a78a "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Wed, 16 Jan 2019 12:08:19 GMT"
TRACE 2019/01/16 17:38:49 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 407
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc"}}
{"Host":"Abhijiitbw81","Pid":5424,"Stats":{"Flushed":12,"Committed":5,"Indexed":0,"Created":0,"Updated":5,"Deleted":0,"Succeeded":5,"Failed":0,"Workers":[{"Queued":0,"LastDuration":163000000},{"Queued":0,"LastDuration":162000000},{"Queued":0,"LastDuration":191000000},{"Queued":0,"LastDuration":11000000}]},"Timestamp":"2019-01-16T12:08:44"}

TRACE 2019/01/16 17:38:49 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":25,"errors":false,"items":[{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc","_id":"DiqQVmgBN2iqLKf8Y5mX","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:39:19 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 407
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc"}}
{"Host":"Abhijiitbw81","Pid":5424,"Stats":{"Flushed":18,"Committed":5,"Indexed":0,"Created":0,"Updated":5,"Deleted":0,"Succeeded":5,"Failed":0,"Workers":[{"Queued":0,"LastDuration":163000000},{"Queued":0,"LastDuration":162000000},{"Queued":0,"LastDuration":191000000},{"Queued":0,"LastDuration":11000000}]},"Timestamp":"2019-01-16T12:09:14"}

TRACE 2019/01/16 17:39:19 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":35,"errors":false,"items":[{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc","_id":"DyqQVmgBN2iqLKf82Jm_","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:39:49 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 407
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc"}}
{"Host":"Abhijiitbw81","Pid":5424,"Stats":{"Flushed":24,"Committed":5,"Indexed":0,"Created":0,"Updated":5,"Deleted":0,"Succeeded":5,"Failed":0,"Workers":[{"Queued":0,"LastDuration":163000000},{"Queued":0,"LastDuration":162000000},{"Queued":0,"LastDuration":191000000},{"Queued":0,"LastDuration":11000000}]},"Timestamp":"2019-01-16T12:09:44"}

TRACE 2019/01/16 17:39:49 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":37,"errors":false,"items":[{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc","_id":"ECqRVmgBN2iqLKf8TZnv","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:40:19 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 407
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc"}}
{"Host":"Abhijiitbw81","Pid":5424,"Stats":{"Flushed":30,"Committed":5,"Indexed":0,"Created":0,"Updated":5,"Deleted":0,"Succeeded":5,"Failed":0,"Workers":[{"Queued":0,"LastDuration":163000000},{"Queued":0,"LastDuration":162000000},{"Queued":0,"LastDuration":191000000},{"Queued":0,"LastDuration":11000000}]},"Timestamp":"2019-01-16T12:10:14"}

TRACE 2019/01/16 17:40:19 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":33,"errors":false,"items":[{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc","_id":"ESqRVmgBN2iqLKf8w5kp","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:40:49 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 407
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc"}}
{"Host":"Abhijiitbw81","Pid":5424,"Stats":{"Flushed":36,"Committed":5,"Indexed":0,"Created":0,"Updated":5,"Deleted":0,"Succeeded":5,"Failed":0,"Workers":[{"Queued":0,"LastDuration":163000000},{"Queued":0,"LastDuration":162000000},{"Queued":0,"LastDuration":191000000},{"Queued":0,"LastDuration":11000000}]},"Timestamp":"2019-01-16T12:10:44"}

TRACE 2019/01/16 17:40:49 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"took":36,"errors":false,"items":[{"index":{"_index":"monstache.stats.2019-01-16","_type":"_doc","_id":"EiqSVmgBN2iqLKf8OJlZ","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}
TRACE 2019/01/16 17:41:19 POST /_bulk HTTP/1.1
Host: localhost:9200
User-Agent: elastic/6.2.14 (windows-amd64)
Content-Length: 407
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip


Could you please tell me there is anything wrong with the configuration?

**Comment by rwynn** [comment]
@abhijitbashetti the behavior you are describing is how it is designed to work with `exit-after-direct-reads=true`.  Set this to`false` or remove the line so that monstache continues waiting for events after the collections are copied.

**Comment by abhijitbashetti** [comment]
Hi Ryan,

Thanks for the reply.
 I modified the configuration to "exit-after-direct-reads = false", 
But still I see the same issue. Anything that is inserted in MongoDB is not reflected to ElasticSearch. :(

**Comment by abhijitbashetti** [comment]
I am looking for full sync + continuous updates to Elasticsearch...

I do not want to restart to the Monstache with  any configuration.

**Comment by rwynn** [comment]
Monstache by default does full sync + continuous updates.  

How are you verifying the insert?

I noticed in your config that you have these 2 not nested in a `mapping`

```
index = "user"
type = "_doc"
```

did you mean to have a mapping config?  this would need to be at the end of the file

```
[[mapping]]
index = "user"
type = "_doc"
```

**Comment by abhijitbashetti** [comment]
I have removed the mappaing ...it does not make any sense for me at this moment.
I am verifying the data on elasticsearch side by firing the below command

curl -XPOST "localhost:9200/test.test/_search?pretty=true"

**Comment by abhijitbashetti** [comment]
Is there anything specific that I am missing on the mongoDB side?

**Comment by rwynn** [comment]
Have you setup a replica set per the instructions [here](https://rwynn.github.io/monstache-site/start/#usage)?  

When you connect to MongoDB using the `mongo` client do you have a `local` db with a `oplog.rs` collection in it?  `oplog.rs` is needed by monstache and is created as the result of setting up a replica set.  Replica set may contain a single member for testing.

**Comment by abhijitbashetti** [comment]
I see local db :  

MongoDB Enterprise > use local;
switched to db local
MongoDB Enterprise > show collctions;
2019-01-16T19:49:38.985+0530 E QUERY    [js] Error: don't know how to show [collctions] :
shellHelper.show@src/mongo/shell/utils.js:1055:11
shellHelper@src/mongo/shell/utils.js:766:15
@(shellhelp2):1:1
MongoDB Enterprise > show collections;
oplog.rs
replset.election
replset.minvalid
replset.oplogTruncateAfterPoint
startup_log
MongoDB Enterprise >

**Comment by abhijitbashetti** [comment]
Hi Ryan,

I have uninstalled the mongoDB. I will install it again and reconfigure it for the replica set.

I will update you on the same tomorrow.

Thanks for your help.

**Comment by sakthiskv** [comment]
Anything that is inserted in MongoDB is not reflected to ElasticSearch. :(

**Comment by sakthiskv** [comment]
[[mapping]]
namespace = "sakthi.inventory"
index = "sakthi.inventory"
type = "_doc"
id="5c7529b03a6fc52f72962483"

gzip = true
stats = true
index-stats = true

# exclude documents whose namespace matches the following pattern
namespace-exclude-regex = '^sakthi\.inventory$'
resume-name ="default"
verbose = true
#replay = true
dropped-databases = true
resume = true
dropped-collections = true
resume-write-unsafe = true
enable-http-server = true

exit-after-direct-reads = false
index-as-update=true

**Comment by sakthiskv** [comment]
mapping also not working

**Comment by rwynn** [comment]
Make sure to read this from the docs.  

Keep simple one-line configs above any TOML table definitions in your config file. A TOML table is only ended by another TOML table or the end of the file. Anything below a TOML table will be interpreted to be part of the table by the parser unless it is ended. See the following Issue 58 for more information.

Make sure you have setup a replica set in MongoDB.

**Comment by rajeshkumarplv** [comment]
@rwynn , Updates and Inserts are not reflecting in Elastic Search after initial sync which is successful. I did enable the oplog for mongoDB server. This is the config.toml I used. I did comment out direct-read-namespaces and restarted the process. But still I see same issue

mongo-url = "mongodb://127.0.0.1:27017/?replicaSet=rs1"
elasticsearch-urls = ["http://localhost:9200"]

#direct-read-namespaces = [ "local.user_info" ]

gzip = true
stats = true
index-stats = true

elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000 

dropped-collections = false
dropped-databases = false

resume = true
resume-write-unsafe = true
resume-name = "default"
index-files = false
file-highlighting = false
verbose = true
exit-after-direct-reads = false

index-as-update=true
index-oplog-time=true
