### ISSUE TITLE
Can't connect to mongo atlas

### ISSUE THREAD

**Issue by pfarah65** [rwynn/monstache#158]
I cannot connect to my mongoDB Atlast server, times out after 15 seconds. 
This is my mongo url 
mongo-url = "mongodb+srv://USERNAME:PASS@MYCLUSTER.mongodb.net/local"
**Unable to connect to MongoDB using URL REDACTED@MYCLUSTER.mongodb.net/local: timed out after 15 seconds**
I can connect to it using mongo with the same url, but I get an error when using monstache.
**This command works from the same server:
/usr/bin/mongo "mongodb+srv://USERNAME:PASS@MYCLUSTER.mongodb.net/local"**

**Comment by rwynn** [comment]
Have you tried without the `+srv` part?  

```
mongodb://USERNAME:PASS@MYCLUSTER.mongodb.net/local
```
I've not tried this 3.6 feature before so not sure the mgo golang driver supports it yet.  

Also, have you tried without connecting directly to `local`.

**Comment by pfarah65** [comment]
Yes, I tried those and it didn't work, thanks anyways, your work is appreciated in the community!

**Comment by pfarah65** [comment]
What do you mean the type of account?
Yes thats correct, same server running monstache.

**Comment by rwynn** [comment]
I just mean a free, basic, pro, enterprise.  I ask because in the past I noticed that the free account had some bugs (could not read the oplog) that the paid accounts did not have.   

When that bug occurred a long time ago I reported it to MongoDB and they fixed it.  So at least at that time monstache was able to connect to Atlas.  I even sent MongoDB a link to a test repo so they could replicate the issue -> https://github.com/rwynn/mgo-atlas-test.  Note, since creating that repo Monstache has undergone lots of changes including switching providers for the mgo driver to https://github.com/globalsign/mgo.

**Comment by pfarah65** [comment]
I'm using the free version, I will check that out thanks.

**Comment by rwynn** [comment]
One more suggestion before I try to reproduce on my end.  Have you tried with a config like this?

```
mongodb://USERNAME:PASS@MYCLUSTER.mongodb.net

[mongo-dial-settings]
ssl = true
```

**Comment by pfarah65** [comment]
Just tried it, I'm still getting "Unable to connect to MongoDB using URL timed out after 15 seconds

**Comment by pfarah65** [comment]
I was able to do a work around and change my link format like this:
mongodb://<USERNAME>:<PASSWORD>@cluster0-shard-00-00-
rb899.mongodb.net:27017,cluster0-shard-00-01-
rb899.mongodb.net:27017,cluster0-shard-00-02-
rb899.mongodb.net:27017/<DBNAME>?ssl=true&replicaSet=Cluster0-shard-
0&authSource=admin

**Comment by rwynn** [comment]
Not sure if this could be related.  Since this is not merged maybe the default auth method is not yet supported? https://github.com/globalsign/mgo/pull/282

**Comment by rwynn** [comment]
Ok, I was able to connect using the following combination:

* Use the old URI format not the one with `mongodb+srv` (so your workaround)
* Append `&authMechanism=SCRAM-SHA-1` to the URL (this is key so that it doesn't use the old default)
* Configure monstache with `change-stream-namespaces` to listen for changes which uses the API instead of the default of trying to connect and tail the `local.oplog.rs` collection.

**Comment by pfarah65** [comment]
Okay thanks for the help!

**Comment by sanchayjain28** [comment]
I am facing the same issue ERROR 2024/03/07 15:29:07 Unable to connect to MongoDB using URL REDACTED@abcd.grouhax.mongodb.net/: timed out after 15 seconds
