### ISSUE TITLE
Not starting from given timestamp on resume-from-timestamp option

### ISSUE THREAD

**Issue by gabrielmcf** [rwynn/monstache#177]
I'm trying to start monstache from some days ago but it seems to stay in today timestamp. I've tried to turn off the `resume` option but it kept updating the timestamp in monstache. The main options in my config.toml are:

```
    mongo-url = REDACTED
    elasticsearch-urls = REDACTED
    resume-from-timestamp = 1549850400
    namespace-regex = "^offers_data.offers$"
    mongo-oplog-collection-name = "oplog.$main"
    resume = false
    routing-namespaces = ["offers_data.offers"]
    verbose = false
    elasticsearch-max-bytes = 1024000000
    elasticsearch-max-conns = 512

    [gtm-settings]
    channel-size = 4096
    buffer-size = 512
    buffer-duration = "150ms"
```

**Comment by rwynn** [comment]
I think you need to have `resume=true` for the `resume-from-timestamp` value to be used.  I think this will change in the next version.  Remember the `resume-from-timestamp` value is a 64-bit number where the high 32 bits are the seconds since epoch. I will probably add a script to the docs on how to generate this number from a MongoDB timestamp in the DB.  Basically, you need the time portion to be shifted 32 bits left.

**Comment by rwynn** [comment]
Can you please try this again with the latest release?

**Comment by gabrielmcf** [comment]
I will give it a try today, thank you for your answer!

**Comment by gabrielmcf** [comment]
I think it worked. Since the documents where older than the ones already in index the timestamp in mongo jumped really fast to a closer date. I would really appreciate a script to convert those timestamps, I'm not sure I did it right...
Thank you for your answer and nice piece of software!
