### ISSUE TITLE
Connecting to replicaSet with SSL

### ISSUE THREAD

**Issue by uday-awv** [rwynn/monstache#201]
Hi,

I am trying to configure monstache to connect to replicaset servers but it is not working.
monstache config
```
# connection settings

# connect to MongoDB using the following URL
mongo-url = "mongodb://elastic:el4st1c1234@db01.antariksh.com:27017,db02.antariksh.com:27017,db03.antariksh.com:27017,db04.antariksh.com:27017,db05.antariksh.com:27017/admin?replicaSet=antariksh-rs1"

mongo-pem-file = "mongodbXX_antariksh_com.pem"
mongo-validate-pem = true

[mongo-dial-settings]
ssl = true
timeout = 30

# verbose = true 
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://antariksh-es6:9200"]
```
#### Console output
```
$ monstache -f monstache-stage-view.toml

ERROR 2019/04/04 14:12:55 Unable to connect to MongoDB using URL mongodb://REDACTED@db01.antariksh.com:27017,db02.antariksh.com:27017,db03.antariksh.com:27017,db04.antariksh.com:27017,db05.antariksh.com:27017/  admin?replicaSet=antariksh-rs1: timed out after 30 seconds
```

However I am able to connect successfully from commandline
```
root@es01:~# mongo  --ssl --sslPEMKeyFile mongodbXX_antariksh_com.pem 'mongodb://elastic:el4st1c1234@db01.antariksh.com:27017,db02.antariksh.com:27017,db03.antariksh.com:27017,db04.antariksh.com:27017,db05.antariksh.com:27017/admin?replicaSet=antariksh-rs1'
antariksh-rs1:PRIMARY>
```

Not sure what I am doing wrong or missing in monstache config. Appreciate any help.
I am using monstache 4.15.1 version

**Comment by rwynn** [comment]
This is probably not related but keep all one line configs above any [toml-table].  See warning at top of page here -> https://rwynn.github.io/monstache-site/config/

```
elasticsearch-urls = ["http://antariksh-es6:9200"]

[mongo-dial-settings]
ssl = true
timeout = 30

```

**Comment by rwynn** [comment]
What happens when you set `mongo-validate-pem = false`?  Same thing?

**Comment by rwynn** [comment]
Also try just for information, with no certificate specified, ssl on, and validate false

```
# mongo-pem-file = "mongodbXX_antariksh_com.pem"
mongo-validate-pem = false

[mongo-dial-settings]
ssl = true
timeout = 30
```

**Comment by rwynn** [comment]
Actually, I just noticed an error in the docs.  The config option must be called 

```
mongo-validate-pem-file = false
```

It's not `mongo-validate-pem`.  That is a error in the docs.

However, I don't think that's the issue.  When testing this locally I get immediate errors like this if the PEM validation fails.

```
vagrant@vagrant:/vagrant/monstache$ go run monstache.go -f ~/test.toml 
ERROR 2019/04/04 16:15:01 Unable to dial MongoDB: x509: certificate is valid for *.vagrant.vm, not localhost
```

Since this is getting a timeout I think maybe the configured MongoDB host is somehow not being reached by monstache.

**Comment by uday-awv** [comment]
Thanks for quick reply. I am seeing same timeout error with above mentioned changes to config
1. moving elastic url above [table]
2. with commenting out pem file and setting mongo-validate-pem-file = false.

It very much looks like monstache is not able to connect. 
Any tips if I can enable more logs to check or good places to add logs in source and do custom monstache build?
I tried `verbose = true` but I guess it is for different purpose.

**Comment by rwynn** [comment]
I’m assuming you are already or have tried running monstache on the same host that is already able to connect using the mongo command?  Are you running in docker as that could factor into the issue?

**Comment by uday-awv** [comment]
yeah I connected from same host using mongo command and running monstache from bash commandline. 
It wasn't working from docker so trying from normal bash to narrow down.

**Comment by rwynn** [comment]
The place to add log statements would be in the dialMongo function in the source of monstache.go. You could print the DialInfo struct in the to see if anything looks wrong. 

The other thing would be to add mgo.Setdebug(true) and mgo.SetLogger(infoLog) to the source code. 

The api is here -> 
https://godoc.org/github.com/globalsign/mgo

**Comment by rwynn** [comment]
Just added a commit with a new -debug flag you can set.

**Comment by uday-awv** [comment]
The error I am seeing is `SYNC Command 'ismaster' to db01.antariksh.com:27017 failed: EOF`.

Alternative I tried with `mongo-x509-settings` with `authMechanism=MONGODB-X509` and it worked with same pem file. This however logged me in with admin permissions.

Do I need to generate different TLS/SSL certificates for username password authentication or am I missing any database permissions to connect with "elastic" user? 
"elastic" user has permissions to "local" database "oplog" collection and "media" database.

Thanks again for patch. Appreciate your help.

**Comment by rwynn** [comment]
That's interesting.  

My understanding is that if you enable SSL with a self-signed cert in MongoDB then one way to make that work is to add the pem file to the `RootCAs` of the `tlsConfig`.  That is for your TLS connection to work and that config is `mongo-pem-file`.  

Now, if you also want to login using certificates instead of username/password, then that is configured via `mongo-x509-settings` and requires 2 pem files (a client cert and client key).  That type of login is described [here](https://godoc.org/github.com/globalsign/mgo#example-Credential--X509Authentication)

I think you should be able to use both SSL and user/password authentication (as you originally configured).  Maybe the problem is related to your URL `27017/admin`? Since this user has access to the `media` database can you try with `27017/media`?  

What version of MongoDB are you connecting to?  I think MongoDB 4+ supports `SCRAM-SHA-1` as an authMechanism.  It looks like the mgo driver will automatically switch to this if authMechanism is not specified and the driver [detects](https://github.com/rwynn/mgo/blob/master/auth.go#L163) a recent wire version.

**Comment by rwynn** [comment]
You may also need to modify the `authSource` in the connection URL.  I think it defaults to `admin` if not specified.

**Comment by uday-awv** [comment]
I am using mongo 4.0.8 version. I tried with `27017/media` and no luck with user/pwd auth. 
To make `MONGODB-X509` work earlier I had to upgrade to `4.16.1` since that had x509 auth fixes. 
I will update here if I can get username/pwd to work with new selfsigned cert using another set of test instances.
Closing the issue as I can go ahead with X509 authentication now. 
Thanks again for all your help.
