### ISSUE TITLE
Error reading segment of collection, i/o timeout

### ISSUE THREAD

**Issue by sasavranic** [rwynn/monstache#211]
For last couple of days I'm playing with this brilliant tool and at first my setup was

* Mongo 4
* ES 6

With latest version of Monstache v5 - everything works brilliant, init sync and everything else.
Now, as my production servers are still with Mongo v3.4, and I can't easily switch it to v4 I tried Monstache version 4.17, so

* Mongo 3.4
* ES 6

And I have lot of these errors 

`ERROR 2019/04/26 08:10:16 Error reading segment of collection XX.XX. Will retry segment.: read tcp xx.xx.xx.xx:46696->xx.xx.xx.xx:27017: i/o timeout`

Because Mongo collection is very big (cca 50 mill of records), I left during night sync, and for example this morning after checking almost nothing is synced to ES, just data from one collection - but even that is not complete.

I already tried to setup different settings in TOML like

`elasticsearch-max-bytes = 800000` 
`elasticsearch-max-conns = 2`
`[mongo-session-settings]`
`socket-timeout=30`
`sync-timeout=30`
`[gtm-settings]`
`channel-size = 1024`

For sync to ES very often etc... What can I setup more?

Also, I have in direct-read just 3 collections from Mongo, not all. 
What is interesting more, if I put in direct-read just one collection - then it will be synced - but partially... If I have setup like this - it will not work

`direct-read-namespaces = ["db.tbl1", "db.tbl2", "db.tbl3"]`

Thanks

**Comment by rwynn** [comment]
Hi @sasavranic you may want to try using the following setting since you mentioned it sort of worked for one collection:

```
direct-read-concur = 1
direct-read-split-max = -1
```
This will ensure that only 1 of the namespaces in `direct-read-namespaces` is syncing at a time instead of all concurrently.  I suspect maybe resources are tight with all at once.  It also reads each collection as one segment (one open cursor) instead of trying to split it into multiple segments and reading multiple open cursors concurrently.  

Also, you can actually try monstache v5 with MongoDB lower than v3.6.  I've not done any testing in this regard but the underlying golang driver supports v3.4.  In monstache v5 you would do that as follows:

```toml
enable-oplog = true
# also make sure you omit any settings like change-stream-namespaces
```

This basically reverts to using to the old method of listening for changes which is to tail the oplog collection in the `local` database.  Obviously your user needs access to this db to listen for changes.

**Comment by sasavranic** [comment]
Hi, thanks for quick response...

Updated suggested params... with version 4 it seams fine now... I will see - it's not fast :)
But with version 5 I have this:

`panic: runtime error: integer divide by zero`

`goroutine 40 [running]:`
`github.com/rwynn/gtm.DirectReadPaged(0xc00083a240, 0xc0009ca000, 0xc0000a4480, 0x1e, 0xc0001b0620, 0x0, 0x0)
	/home/vagrant/go/pkg/mod/github.com/rwynn/gtm@v0.0.0-20190419152047-ef943df44083/gtm.go:1318 +0xcd6`
`created by github.com/rwynn/gtm.ProcessDirectReads
	/home/vagrant/go/pkg/mod/github.com/rwynn/gtm@v0.0.0-20190419152047-ef943df44083/gtm.go:1108 +0x1d4`

**Comment by rwynn** [comment]
Try 1 instead of -1 for direct read split max.  There may be a bug in v5 related to that.

**Comment by sasavranic** [comment]
Ohh tnx will try.

**Comment by sasavranic** [comment]
So far with v4 is good.

**Comment by sasavranic** [comment]
I'm just interested in following. When I stop service and start again it will scan mongo again (oplog) from beginning? Because I'm planning to use this tool in production in combination with ruby ES gems just without  hooks. So far I have good impression, everything works very good. So what if tool fails at some point and needs to be restarted or simply server maintenance.

**Comment by rwynn** [comment]
If you use resume=true then subsequent restarts should start where previous left off. That is for change events. 

If you specify direct reads then those copy entire collections. Resume does not apply here.

**Comment by sasavranic** [comment]
Hi Ryan, sorry for delay. I tried version 5 with parameter 1 as you suggested but still read i/o... Version 4 is ok.
Ok, I think switching to Mongo v4 is way to go anyway.
