### ISSUE TITLE
Error using change stream in HA mode with MongoDB 3.6

### ISSUE THREAD

**Issue by gorjuspixels** [rwynn/monstache#212]
First of all, thank you for the this awesome tool. There really isn't another one like it.

I'm having an issue when running monstache in high availability mode and using change streams against MongoDB v3.6. I'm using monstache v4.17.1, but I've had the same issue on v5.0.1.

I get the following errors:

```
ERROR 2019/04/29 06:15:29 Error starting change stream. Will retry.: BSON field '$changeStream.startAtOperationTime' is an unknown field.
ERROR 2019/04/29 06:15:29 Error starting change stream. Will retry.: BSON field '$changeStream.startAtOperationTime' is an unknown field.
INFO 2019/04/29 06:15:34 Direct reads completed
ERROR 2019/04/29 06:15:34 not authorized on admin to execute command { replSetGetStatus: 1, $db: "admin" }
ERROR 2019/04/29 06:15:34 Error starting change stream. Will retry.: BSON field '$changeStream.startAtOperationTime' is an unknown field.
ERROR 2019/04/29 06:15:34 Error starting change stream. Will retry.: BSON field '$changeStream.startAtOperationTime' is an unknown field.
```

There are 2 errors - one coming from change stream and the other right after direct reads are performed. Both errors disappear when I turn off cluster mode.

My `config.toml`:

```
mongo-url = "mongodb://user:password@mongodb:27017/test?replicaSet=test-shard-0&ssl=true&authSource=admin"
elasticsearch-urls = ["https://user:password@elasticsearch:9243"]

direct-read-namespaces = ["db.test","db.test1"]
change-stream-namespaces = ["db.test","db.test1"]

prune-invalid-json = true

gzip = true

elasticsearch-retry = true
elasticsearch-client-timeout = 60
elasticsearch-healthcheck-timeout = 15

[mongo-session-settings]
socket-timeout = 30
sync-timeout = 60

[mongo-dial-settings]
read-timeout = 60
write-timeout = 60

[[mapping]]
namespace = "db.test"
index = "test"

[[mapping]]
namespace = "db.test1"
index = "test1"
```

I'm setting cluster name through the `MONSTACHE_CLUSTER` environment variable.

Is MongoDB v4 required to use HA mode AND change streams?

**Comment by rwynn** [comment]
Hi @gorjuspixels.  MongoDB v4 is required to use HA mode in conjunction with change streams.  When HA mode is enabled monstache automatically turns on `resume`.  Resume is turned on to ensure that if a monstache process goes down another process in the cluster will take up the work at the last saved timestamp from the first.  However, the way monstache accomplishes this when change streams are enabled is to the use the `startAtOperationTime` query config on the change stream which is only supported starting in MongoDB 4.0.  If change streams are not used, then the mechanism to resume a stream is different.  The timestamp in that case is simply a filter into the query performed directly on the oplog collection.  Since this is a normal query this mode of operation does not required MongoDB 4.0.  

The 2nd error that you noticed about the `replSetGetStatus` command is related to HA mode turning on `resume`.  When `resume` gets enabled and direct reads are completed monstache will attempt to read and store the most recent timestamp as reported by the command.  This change was in response to issue #203.  In this case the user you are connecting with does not have permission to run that admin command so the timestamp is not being stored.  This is not necessarily a fatal error, it just means for the purposes of resuming the only timestamps that will be stored are those coming from changes.

**Comment by gorjuspixels** [comment]
Makes sense. So I need to either use oplog instead of change streams or upgrade to MongoDB 4.0 👍.

And thank you for explaining the second error. I was able to resolve it by adding `clusterMonitor` privilege to the database user (I'm using Atlas).

**Comment by rwynn** [comment]
@gorjuspixels just FYI if you wished to used the oplog with Monstache v5 you can still do that.  But in that case you need the following settings since in v5 and v6 change streams are given preference over direct access.

```
enable-oplog = true
# also make sure you omit any settings like change-stream-namespaces
# and that read access to local db is opened up in Atlas
```
The only reason to use v5 instead of v4 currently is if you wish to use the new golang driver from MongoDB.  This [driver](https://github.com/mongodb/mongo-go-driver) is fairly new but has alot of activity around it and will probably keep up with new features more rapidly.  For example, it should support `mongodb+srv` connection strings already. 

And the only difference between monstache v5/v6 is that they are designed to work with Elasticsearch 6/7 respectively (they reference different versions of the Elasticsearch client).  Mostly that means v6 does not index with the `type` field set to remove deprecation warnings.
