### ISSUE TITLE
Plugin version error

### ISSUE THREAD

**Issue by IchorPop** [rwynn/monstache#214]
I'm attempting to run Monstache with the plugin (built from the build.sh file in /docker/plugin). Upon running `monstache -mapper-plugin-path /path/to/myplugin.so` I get the error:

> plugin was built with a different version of package github.com/mailru/easyjson/jlexer

The odd thing is that I have run monstache via this route with no problem before (a couple of months ago).

**Comment by rwynn** [comment]
Hi @IchorPop 

Do you think it could be a mismatch between the version the plugin was built against and the version it was run against?

| Monstache version      | Git branch (used to build plugin) |  Docker tag | Description
| ----------- | ----------- |------------|---------
| 3      | rel3       |  rel3 | mgo community go driver, supports Elasticsearch 2 and 5
| 4   | master        | rel4 (note this used to be latest) | mgo community go driver, supports Elasticsearch 6
| 5      | rel5       |  rel5 | MongoDB, Inc. go driver, supports Elasticsearch 6
| 6      | rel6       |  rel6, latest | MongoDB, Inc. go driver, support Elasticsearch 7

I have yet to find the time to update the docs since version 5 and 6 were added.  

Note: I think the best way to build a plugin and use with Docker is to

1. Check out a specific version tag, e.g. `v4.17.2`, from git
2. Build the plugin
3. Run with docker using the same version tag, e.g. `rwynn/monstache:4.17.2`

**Comment by IchorPop** [comment]
Hi, thanks! Yes, I was using the "latest" tag, whereas I needed version 4.17.2 instead.
