### ISSUE TITLE
whether support batch size sync setting from mongo db's one collection to elasticsearch?

### ISSUE THREAD

**Issue by sunweiconfidence** [rwynn/monstache#241]
hi Rwynn,
I have a question for batching sync mongo collection's document to elasticsearch, now config.toml don't have introduction for batch size one time, by default what's the batch size for one time batch sync to elasticsearch? whether support batch size setting in config file and then sync? thanks

**Comment by rwynn** [comment]
hi @sunweiconfidence batch of what?  documents sent to Elasticsearch?  Documents are sent in a bulk request with multiple docs according to when the following limits are reached: `elasticsearch-max-bytes`, `elasticsearch-max-docs` and `elasticsearch-max-seconds`.  

Or are you talking about something different.

**Comment by sunweiconfidence** [comment]
hi Rwynn, I mean documents send to elasticsearch for every time, elasticsearch's bulk insert can be set in advance in config file

**Comment by rwynn** [comment]
If you always want 100 documents to be sent in a bulk then you need to turn off the auto flush timer and the max bytes and turn on the max docs.

```
elasticsearch-max-seconds = -1
elasticsearch-max-bytes = -1
elasticsearch-max-docs = 100
elasticsearch-max-conns = 1
```

Each conn (in this case 1) will wait till 100 documents are reached and then flush.  If you have 2 conns then the documents would be spread across the 2 conns and each would still only flush after 100 documents. 

Since the max seconds is turned off this will never flush until at least 100 documents is reached.  This can be problematic since if you have only 99 docs you will never see them in Elasticsearch.  That is the purpose of max-seconds.  Max seconds will flush whatever it has currently after the timeout is reached.  You can set it to 30 or higher if you want less than 100 docs to eventually flush.  

Is this what you mean?

**Comment by rwynn** [comment]
There is no per collection setting for the Elasticsearch bulk request size.  The settings apply to each Elasticsearch conn and each conn may get documents from multiple MongoDB collections.

**Comment by sunweiconfidence** [comment]
yes, This is what i mean, but for your point "The settings apply to each Elasticsearch conn and each conn may get documents from multiple MongoDB collections", i am confused with it, if i select three collections to sync to three seperate elasticsearch index seperately in three different config file,such as 
collection1 -> config1.toml
collection2-> config2.toml
collection3-> config3.toml
 can't set elasticsearch-max-docs in own config file?

**Comment by rwynn** [comment]
Yes, you can run 3 separate process with 3 separate configs.  I was just saying that for each process there is only 1 configuration for bulk size.  When the documents are read from MongoDB they go to whatever Elasticsearch conn is ready to pick them up.  There are 4 conns by default.  That means that if you have batch size set to 100 docs, and you make 4 changes in MongoDB, those 4 docs will be spread across the 4 conns.  So each conn might have only 1 doc after 4 changes.  The bulk size you set applies to each conn not to the entire set.  That is why I set conns to 1 above to make it simple.  With 1 conn, 100 changes with a bulk size of 100 = flush.

**Comment by sunweiconfidence** [comment]
ok, thanks, i understand it
