### ISSUE TITLE
Investigate mongo+srv dns issues with docker

### ISSUE THREAD

**Issue by rwynn** [rwynn/monstache#252]
Since there have been some comments about not being able to connect via mongodb+srv due to dns issues I will post this link here. 

https://stackoverflow.com/questions/55989902/lookup-google-com-on-192-168-65-153-cannot-unmarshal-dns-message

The issue seems to be around a change to how dns works starting in go 1.11. Monstache is built with go 1.12. 

If you run into issues with dns check the link above.  It’s possible that depending on your dns env you will not run into problems. 

There is also related info on the Golang driver page. 

https://jira.mongodb.org/plugins/servlet/mobile#issue/GODRIVER-829

**Comment by Gamiot** [comment]
Hello Rwynn,

I do not know if this information will be related to your issue but i came up with a DNS issue when using docker (in another context than Monstache) . 

Docker is very permissive in regards on naming of the services.  It is allowing to create host name in its internal network that would normally not be allowed. For instance, we added a service with the following  name: "my_service". It turned out that some application running in our container were rejecting it  because of the underscore character (_). The error message was not clear why it was not working. 

It turned out by changing the host name to myservice resolved the issue.
