### ISSUE TITLE
why version conflict?

### ISSUE THREAD

**Issue by mowenlong** [rwynn/monstache#257]
The version I use is monstache:4.17.5   MongoDB:3.2.10 Elasticsearch:6.8.1
Why is there error?

INFO 2019/07/12 11:09:21 Started monstache version 4.17.5
INFO 2019/07/12 11:09:21 Successfully connected to MongoDB version 3.2.10
INFO 2019/07/12 11:09:21 Successfully connected to Elasticsearch version 6.8.1
INFO 2019/07/12 11:09:21 Listening for events
ERROR 2019/07/12 11:11:55 Bulk response item: {"_index":"papercheck.paper","_type":"_doc","_id":"5d27f9eca94e6204cf667e8a","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[_doc][5d27f9eca94e6204cf667e8a]: version conflict, current version [6712609175806935045] is higher or equal to the one provided [6712609175806935044]","index":"papercheck.paper"}}
ERROR 2019/07/12 11:12:13 Bulk response item: {"_index":"papercheck.paper","_type":"_doc","_id":"5d1d989ca94e6204cf648afb","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[_doc][5d1d989ca94e6204cf648afb]: version conflict, current version [6712609253116346375] is higher or equal to the one provided [6712609253116346369]","index":"papercheck.paper"}}

**Comment by rwynn** [comment]
If old events are replayed they will be rejected since newer data already exists in Elasticsearch. Are you replaying old events?  

You can usually ignore this type of error.

**Comment by mowenlong** [comment]
> If old events are replayed they will be rejected since newer data already exists in Elasticsearch. Are you replaying old events?
> 
> You can usually ignore this type of error.

hello
There are too many errors in this report.Running for more than ten minutes, the number of error-guaranteed rows reaches more than 100,000 rows.
How do you handle this?
My log hard disk will soon be full.Is there any other parameter that can be set to not report this error?

**Comment by mowenlong** [comment]
> If old events are replayed they will be rejected since newer data already exists in Elasticsearch. Are you replaying old events?
> 
> You can usually ignore this type of error.

hello
There are too many amount in this error.my program have  large amount of concurrency, Running for more than ten minutes, the number of this error(version_conflict_engine_exception) rows reaches more than 100,000 rows.
How do you handle this?
My log hard disk will soon be full.Is there any other parameter that can be set to not report this error?

**Comment by rwynn** [comment]
Do not use `replay` true.  If you are not replaying and getting the version conflict then let me know.

**Comment by mowenlong** [comment]
> Do not use `replay` true. If you are not replaying and getting the version conflict then let me know.

I use replay = false, but i also getting the version conflic,
when i user replay = false,index-as-update = true i don't getting the version conflic.

**Comment by rwynn** [comment]
If you don't replay then you shouldn't get version conflict.  Version number comes from MongoDB oplog timestamp which should increase over time.  For direct reads version number comes from current system time.  It is possible to get version conflict if doing lots of inserts while also doing direct reads.

**Comment by rwynn** [comment]
@mowenlong version conflict messages should now be suppressed as errors in the latest release.

**Comment by ywilkof** [comment]
@mmwl Another reason for getting version conflicts when replay = false is due to concurrency and high number of updates to the same documents in a short period of time. 

In a high volume setup it is possible that a document in Mongo is being created / updated multiple times within milliseconds. Due to the existence of concurrent workers it might be that a later version of the document will be indexed by one worker, before the document with an earlier version is indexed by another worker. 

@rwynn is this a possible scenario?

**Comment by rwynn** [comment]
hi @ywilkof  

monstache uses the `clusterTime` field from the MongoDB [change event](https://docs.mongodb.com/manual/reference/change-events/) converted to an integer as the version number of the corresponding document in Elasticsearch.  

So by default under your scenario monstache should get a version conflict on the request with the old data.  This is expected since this is an older version than what is currently indexed.  

When monstache is configured with [index-as-update](https://rwynn.github.io/monstache-site/config/#index-as-update) enabled (not the default), then this version number field is not sent to Elasticsearch and you would potentially have issues with the ordering.

**Comment by philbannon** [comment]
Hi @rwynn  hope you're well.

I'm getting this same issue on my test environment. I'm the only user on this environment (both mongo and ES). When I create  a doc in Mongo db, I receive the same error and I'm not doing multiple updates etc.

what's strange in my case is that some of date from mongo is getting sent to ES but not all of it.  In my case i have an one element of my mongo doc which is not showing up in the ES document

**Comment by philbannon** [comment]
Also if it helps, I've deleted my ES index and my mongo collection. Once I create a new mongo doc (and collection) I still get the version conflict. 

Also replay = false in my config

Thanks @rwynn

**Comment by philbannon** [comment]
Ok so, I figured out why I was getting this error. So I had accidentally kicked off two monstache instances both watching for changes in Mongo and replicating them to ES. 

@rwynn is it a bug or more an issue with my dumb self ;)

**Comment by rwynn** [comment]
Hi @philbannon I'm pretty sure it's just the way monstache is designed.  It uses MongoDB timestamps as Elasticsearch version numbers and sets version_type to `external`.  This is because due to the way it uses go routines even a single monstache process may send updates for the same document id out of order.  

> With version_type set to external, Elasticsearch will store the version number as given and will not increment it. Also, instead of checking for an exact match, Elasticsearch will only return a version collision error if the version currently stored is greater or equal to the one in the indexing command. This effectively means "only store this information if no one else has supplied the same or a more recent version in the meantime".

from https://www.elastic.co/blog/elasticsearch-versioning-support.

If you do want to run 2 instances of monstache and not have them send the same documents to Elasticsearch you can configure as [workers](https://rwynn.github.io/monstache-site/advanced/#workers)
