### ISSUE TITLE
Infinite time cluster wait when get isDup() error

### ISSUE THREAD

**Issue by azatbek** [rwynn/monstache#262]
Hi, I'm using monstache rel6, and sometimes when I get "mongo: no documents in result" from mongo.client, daemon going to clusterWait mode. But its waiting for infinite time, because if I restart it manually everything works fine. Is there program should exit when gets isDup() type error?

**Comment by rwynn** [comment]
Hi, just so we are on the same page, are you setting a value for `cluster-name`?

When you set `cluster-name` monstache goes into a different mode of operation.  This mode is designed for use with multiple monstache processes and is not needed if you have only 1 monstache process. 

The cluster mode works to ensure that all processes sharing the same value of `cluster-name` coordinate.  This means that 1 will be the primary (actively syncing) and the others secondary (waiting to become the primary if needed).  

In this mode monstache uses the collection `monstache.monstache` by default to facilitate this coordination.  Each process will try to write to this collection using the same `_id`.  If the write succeeds the process will be the primary.  If the write fails via a duplicate record then the process will be a secondary.  

The docs in this collection will time out and be removed by MongoDB due to an index on the collection named `expireAt`.  A primary process will periodically update the `expireAt` field to signal that it is running and prevent MongoDB from removing the record.  This ensures that secondary processes remain inactive.  The secondary processes will try to insert a record but fail due to the record being a duplicate.  

If the primary is stopped it will no longer be able to perform this update that extends the timeout.  In this case MongoDB will expire and remove the document.  At this time one of the secondary processes will no longer fail to insert a doc due to a duplicate error.  When this happens the 1st secondary that succeeds will become a primary and start syncing.  

Does this explain why not exiting when isDup() is triggered is the desired behavior?  isDup() simply means that at this time the secondary cannot become the primary and to try again later.
