### ISSUE TITLE
Elastic search has duplicate docs

### ISSUE THREAD

**Issue by baid86** [rwynn/monstache#266]
I believe the same issue has been reported earlier as well, may be more than once.
I was doing Mongo to Elastic Search sync for > 10m docs. After initial sync Elastic Search has more docs then mongo.
It looks like elastic monstache created duplicate copies of some data.
My config is like

```
namespace-regex = '^notifications\.event$'
direct-read-namespaces = ["notifications.event"]
change-stream-namespaces = ["notifications.event"]
stats=true
enable-oplog = true
```

MongoDB server version: 3.6.10
Elastic Search Version: 7.2.0

by looking at the eTime which is basically the timestamp from my app which generate the event and also the _ids in docs and notices how closely they are, I am suspecting its a double write from monstache. 
[output.txt](https://github.com/rwynn/monstache/files/3441759/output.txt)

**Comment by rwynn** [comment]
I have not been able to reproduce this.  If you index the same _id twice you only get 1 doc not 2.

**Comment by rwynn** [comment]
This can happen in the following example scenario.  You index some data with Monstache v6.  You later upgrade Monstache to v6.1 which includes a fix for serializing UUID and thus generates different _id for UUID fields.  

https://github.com/rwynn/monstache/issues/243

You index again with v6.1 and now you have duplicate records because the upgrade changed how those _id were generated (hopefully for the better).   

These type of fixes happen infrequently but they do happen. 

ObjectID fields have always been the hex representation since the beginning of monstache and that hasn't changed.

**Comment by baid86** [comment]
>  You index again with v6.1 and now you have duplicate records because the upgrade changed how those _id were generated (hopefully for the better).

This is not the case as i said it was my initial sync.

> I have not been able to reproduce this. If you index the same _id twice you only get 1 doc not 2.
Generally this is the case but I believe there is some race scenario when this can occur. I can consistently reproduce this. If there is some debug logs which I need to enable I can do that and redo the sync. Will `verbose=true` help or it would be too much logs considering the size of my DB

**Comment by rwynn** [comment]
Monstache does depend on the guarantee that Elasticsearch will only ever index 1 document per index per _id. 

I think I would need instructions for a small sized reproduction of the problem. I’ve not seen it happen myself in test runs with 20 million docs.

**Comment by jodevsa** [comment]
Looking at the `output.txt`,  there is not duplicate documents (document with same Id). Your elastic index isn't synced right.

**Comment by jodevsa** [comment]
Also, 

This might be a filtering problem, is mac defined as a keyword in your index? did you check if the results has the same MAC you're filtering with ?

**Comment by rwynn** [comment]
Thanks jodevsa. I was thinking multiple _id but I think you are right this is just a case of a filter that is not doing a literal match. I agree the mac field should be a keyword.

**Comment by rwynn** [comment]
Also could try with a term query for exact match

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

**Comment by rwynn** [comment]
Also in the given example the Mongo query is a findOne (stops at the first match) l so changing that to a find() might also return similar results to the Elastic query.

**Comment by jodevsa** [comment]
@rwynn  

Or could be a bug in the application logic, 
The other 3 documents, which he claimed to be not in sync,  are actually created after `5d1f248cdac3180b255889bb`.  https://steveridout.github.io/mongo-object-time/

**Comment by rwynn** [comment]
@baid86, I think @jodevsa brings up a lot of good questions.  Can you try some of the following experiments?  Sorry, I think I misread your initial points and took the conversation in the wrong direction.  

1. The queries you posted compare an Elastic _search by mac to a MongoDB findOne() by mac.  It's important that we know if a MongoDB find() by that same mac returns more than 1 document.  This may explain why the _search by mac is returning multiple results.  

2.  Can you verify that those macs in the 4 _search hits are all exactly the same and match your query value exactly.  I assume they are since you used <SOME_MAC> for all, but just want to make sure. 

3. Along the same lines as 1, what do you get when you run the following queries on MongoDB?

```
db.event.findOne({_id: ObjectId('5d3e9eece10d07e0df8a3b7f')})
db.event.findOne({_id: ObjectId('5d3e9ec3e10d07e0df8a3b7e')})
db.event.findOne({_id: ObjectId('5d3e9303e10d07e0df8a3b7d')})
```

**Comment by baid86** [comment]
Hi @rwynn I did the stupid oversight of ignoring that my query has findOne instead of find. Sorry for that because that took the conversation in whole different direction. And yes there seems to be some issue at app logic because we have multiple event almost at the similar time. 

Although there are still 2000 extra docs on the elastic side as compared to mongo If I just look at the count. I will try to iterate elastic to get the exact list of docs which are missing in mongo.

**Comment by baid86** [comment]
Hi @rwynn the records are exactly same, Its just that mongo has an issue with the count and its not fully reliable as mentioned [here]. (https://docs.mongodb.com/manual/reference/method/db.collection.count/)
I am closing the issue as monstache works perfectly and its only db.count API of mongo which got me confused.
