### ISSUE TITLE
Loops in Error starting change stream with newest  rwynn/monstache:rel6

### ISSUE THREAD

**Issue by Ognian** [rwynn/monstache#268]
config worked OK with the release 1 month ago; now I get an endless loop with
```
ERROR 2019/08/02 11:27:55 Error starting change stream. Will retry.: (Location40576) Resume of change stream was not possible, as the resume point may no longer be in the oplog. 
ERROR 2019/08/02 11:28:03 Error starting change stream. Will retry.: (Location40576) Resume of change stream was not possible, as the resume point may no longer be in the oplog. 
...
```
I have `replay = true` and `resume = false`, so it should reindex everything 
What does `Location40576` mean??

**Comment by rwynn** [comment]
I think replay needs work. It’s a hack right now that attempts to find the last timestamp in the oplog and start a change stream from it. 

You can try -resume-from-timestamp or just use direct-read-namespaces if you need something like replay.

**Comment by rwynn** [comment]
The error message is from MongoDb. I have no idea what Location40576 means.

**Comment by Ognian** [comment]
OK, now I do not use `replay`. I use `direct-read-namespaces = ['']`and `namespace-exclude-regex = ...`to exclude some of the databases and collections. This works with the latest release. One pitfall is that direct-read-namespaces does not allow wildcards... So therefore I use an array with the empty string witch means everything and exclude via namespace-exclude-regex ...
Thanks
Ognian

**Comment by rwynn** [comment]
Did you mean you now use direct-read-dynamic-exclude-regex? That allows you to ignore collections when Monstache is configured to find all of them for direct reads.

**Comment by Ognian** [comment]
I have not found `direct-read-dynamic-exclude-regex`, so I am using `namespace-exclude-regex`
Good to know that there is this option too...
My biggest problem is actually that the config is "static" and I have to change parameters in the file and rebuild docker, when I need different behave... although this goes also quite quick it is error prone ... I rather need some interface with actions like `stop`, `start with config A`, `stop`. `start with config B` etc...

**Comment by rwynn** [comment]
Many of the options support environment variables. Not sure if that helps.

**Comment by rwynn** [comment]
@Ognian I think I know now what the original problem was with replay.  I was able to replicate the problem on my end.  

Some background on replay is that older versions of Monstache used direct queries on the MongoDB oplog.  When replaying this way Monstache would simply set the ts value in the query to 0 since the query was designed to find all documents > ts.  

This worked pretty well, however going directly against the oplog has a bunch of downsides.  It doesn't work easily for sharded clusters and there is a newer, better API which is change streams that works seamlessly for sharded clusters.  

So, more recent versions of Monstache use the change streams API. 
https://docs.mongodb.com/manual/reference/method/db.collection.watch/

When replay is enabled monstache sends the query argument `startAtOperationTime` described in the link above.  But one cannot simply set this value to 0 as described above.  This is because this API requires a ts that **actually exists currently** in the oplog.  So, what does monstache do but query the oplog directly to find the 1st timestamp.  Once it gets this timestamp it uses it as the value for `startAtOperationTime`.  

Now here is where is gets interesting and is the cause of your original problem.  The oplog is a capped collection and mongodb writes to it often. Sometimes the writes are for operations on your collections, but sometimes the writes are internal bookkeeping that MongoDB does.

When the oplog reaches capacity the oldest entries will be dropped very often.  So, I experimented and found that when the oplog is full often monstache will query for the first oplog entry, and quickly afterwards MongoDB will insert into the oplog causing that oldest entry to be deleted (capped collection).  Then when monstache uses the timestamp in the change stream API it is gone and thus you get that error you found.  

So, one solution I found is to actually increment the timestamp found in the query to get the old timestamp (factoring in that this ts may leave the collection) by something like 10s.  And this worked for me.  I no longer got the error.  So I will implement that in the next release.  

Hopefully, what I described above convinces you that using replay is not a reliable way to sync everything though.  Since the oplog is a capped collection docs will drop off.  So I still suggest that one uses direct-read-namespaces for full sync.

**Comment by Ognian** [comment]
@rwynn thanks a lot for this explanation. Of course I will use direct-read-namespaces; but it also shows that we need to know if Monstache is "keeping up" with mongodb. What I mean is that if elastic slows down, due to to much work, or bad scaling, we need a reliable indicator of that, so that we can initiate a manual resync from some kind of admin program...
