### ISSUE TITLE
x509 Certificate Error v5.1.1

### ISSUE THREAD

**Issue by marcelhdl** [rwynn/monstache#280]
Hi Guys,

when I am using Monstache 5.1.1  im getting the following Error, when trying to connect to the ElasticDB:
ERROR 2019/09/13 12:07:55 Unable to create Elasticsearch client: health check timeout: Head https:/**url**: x509: certificate signed by unknown authority: no Elasticsearch node available

Using the Version 5.0.4 worked for me.
Please have a look on it.

```#DEV
mongo-url = "mongodb://admin:$MONGOPASSWORD@$MONGOURL/ibmclouddb?authSource=admin&replicaSet=replset&sslcertificateauthorityfile=/var/cert.crt&ssl=true&readPreference=secondaryPreferred"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["https://$ELASTICUSER:$ELASTICPASSWORD@$ELASTICURL"]

change-stream-namespaces = ["collection"]
direct-read-namespaces = ["collection"]
verbose = true
#Mapping the nameSpace of Mongo with Index of ES
[[mapping]]
namespace = "collection"
index = "index"```

**Comment by rwynn** [comment]
Hi @marcelhdl 
I think this problem is caused by a security bug fix in [v5.0.11](https://github.com/rwynn/monstache/releases/tag/v5.0.11).  Previous to that release the `elasticsearch-validate-pem-file` config was defaulting to `false` if you provided a config file.  It should have defaulted to `true`.  

After v5.0.11 if you need to turn off validation set:

```
elasticsearch-validate-pem-file = false
```
That should get you back to the behavior you saw in v5.0.4.  

You can also provide a cert for Elasticsearch via the `elasticsearch-pem-file` config.

**Comment by marcelhdl** [comment]
worked! Thx for your help 😜

**Comment by marcelhdl** [comment]
worked! Thx for your help 😜
