### ISSUE TITLE
ingest attachment processor setting for indexed_chars

### ISSUE THREAD

**Issue by cmicallef** [rwynn/monstache#299]
Hi, I am using monstache 6.22 to index PDF's in Gridfs but I noticed that most of the files are getting  truncated to 100000 and it seems monstache sets ingest attachment with the following settings  below which defaults "indexed_chars" to 100000,  is there an option in monstache so that one can set the  "indexed_chars"  property to -1,  this should allow for the indexing of the whole PDF. 
Not sure, if such setting already exists in monstache or if I can override "indexed_chars" globally in Elasticsearch, any tips highly appreciated.

Thanks  

PUT /_ingest/pipeline/attachment
{
  "description" : "Extract file information",
  "processors" : [
    {
      "attachment" : {
    "field" : "file"
      }
    }
  ]
}

**Comment by rwynn** [comment]
Hi @cmicallef,

I've purposefully tried to keep monstache out of the business of setting Elasticsearch configuration options unless necessary, preferring to send data only and leave the configuration to end users.  This might be a case where it is necessary, but first can you try the solution below:

I think in this case the best way to fix this is with an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/indices-templates.html) that you would create that have a pattern defined matching all of the indexes that monstache is sending attachments to.  In this index template you would define the setting for `index.mapping.attachment.indexed_chars`.

If you see the following link it shows how to set this configuration for a **single** index..

https://github.com/elastic/elasticsearch-mapper-attachments/issues/16

You could do that, but I would suggest defining that setting using an index template.  Index templates are applied to new matching indexes at creation time.  So with the index template would would only have to define this setting once and every index created thereafter would get the setting.

Since index templates are applied to indexes at index creation time you would need to delete existing indexes, create the index template, and run monstache again with the template in place. 

If you didn't want to delete existing indexes, you could apply the setting directly to the index as shown in the link above, but the setting would not retroactively apply to documents already indexed, only to new ones.

**Comment by rwynn** [comment]
Hi @cmicallef,

I'm sorry I think my last comment only applies to the older mapper attachments plugin.  Please disregard.  I think the new plugin might require that the settings are attached to the pipeline and not the index.

Can you try creating the same pipeline manually that monstache is creating, but adding the setting `indexed-chars` = `-1`?  Then run monstache again.  

It's possible that when you run monstache again it will overwrite this pipeline entirely (obviously not what we want), but hopefully that's not the case and the settings will be merged. If not merged but overwritten just let me know and I will add an option to monstache.

**Comment by cmicallef** [comment]
Hi Wayne,

 

Thanks for the prompt reply, I had tried setting the index_chars: -1 in the pipeline but unfortunately once I run monstache  it gets overwritten back to .

 

PUT /_ingest/pipeline/attachment
{
"description" : "Extract file information",
"processors" : [
{
"attachment" : {
"field" : "file"
}
}
]
}

**Comment by rwynn** [comment]
@cmicallef I put a workaround in monstache 6.2.3 such that if you set `disable-file-pipeline-put` to true monstache won't try to create/overwrite the pipeline.  You just need to ensure you make a call like this once before running monstache...

```
PUT _ingest/pipeline/attachment
{
  "description" : "Extract file information",
  "processors" : [
    {
      "attachment" : {
        "field" : "file",
        "indexed_chars": -1
      }
    }
  ]
}
```

**Comment by cmicallef** [comment]
Hi Wayne,

Workaround works well 

Thank You for the great support
