### ISSUE TITLE
Failed to connect to MongoDb after upgrate from ver. 4 to 6

### ISSUE THREAD

**Issue by DanBrk** [rwynn/monstache#308]
I tried to upgrade from version 4 to 6 got an error.
I did not change anything, I just replaced the 'monstache.exe'
The error is:

> Unable to connect to MongoDB using URL mongodb://REDACTED@[server-ip]:27017: server selection error: server selection timeout
> current topology: Type: ReplicaSetNoPrimary
> Servers:
> Addr: [server-ip]:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(redis04.snsmart.co.il:27017[-122]) connection is closed
> 

After replacing back to ver. 4 everything works fine.

**Comment by rwynn** [comment]
@DanBrk can you issue the command `rs.status()` in the MongoDB shell and then verify a primary member and also verify that your connection string is using the **same hostname** that is in the `name` attribute of the primary member. 

The difference between 4 and 6 is that 6 uses the official [MongoDB go driver](https://github.com/mongodb/mongo-go-driver/releases) instead of the mgo community driver.

**Comment by rwynn** [comment]
@DanBrk this [link](https://stackoverflow.com/questions/56393513/docker-and-mongo-go-driver-server-selection-error) has more explanation that may help

**Comment by DanBrk** [comment]
Fixed by adding 'connect=direct' to the connection string parameters.
Thanks for your help 👍
