### ISSUE TITLE
elastic.v6?

### ISSUE THREAD

**Issue by remotejob** [rwynn/monstache#32]
Is planned make support for elastic.v6? If so, about when?

**Comment by rwynn** [comment]
Is there a feature of elasticsearch 6 that you would like to see?  Is there any problem running this as is against elasticsearch 6?  Thanks.

**Comment by remotejob** [comment]
I am not tried yet, as well I am not tried with ES5.0.
But I make a note:

elastic "gopkg.in/olivere/elastic.v5"
in yours code

I think must be
elastic "gopkg.in/olivere/elastic"

You have installed Elasticsearch 6.0.0 and want to use Elastic. As listed above, you should use Elastic 6.0.
import "github.com/olivere/elastic"

**Comment by rwynn** [comment]
@remotejob,

I have tested today with ES 5 and 6 and both work fine with the current monstache.  I was able to run monstache's go test program successfully and also use the gridfs feature to index attachment content.  

Monstache uses only a subset of the Elasticsearch API via the REST interface (most importantly the _bulk endpoint) to index documents.  It turns out that this interface has not changed in a way in ES 6 that would make monstache incompatible.  

Also, the package you referenced is not quite [stable](https://github.com/olivere/elastic#releases) yet.  When that becomes stable I will move monstache over to it and retire the use of `gopkg.in/olivere/elastic.v5` which is currently the most recent stable package.  

The most dramatic change in ES 6 is the move to one type per index.  Monstache has for a long time (since version 2.0) defaulted to mapping each MongoDB collection to its own index.  This approach syncs well with the direction ES is going.  

Monstache will, by default, create one index per collection and use the collection name as the ES type for all documents.  This is a different approach to some other programs that do sync between Mongo and ES.  Some of those systems were designed, at least initially, to map an entire MongoDB database to one ES index and use the MongoDB collection name as the ES type.  This design would not work well in ES going forward due to the fact that ES will require 1 type per index - eventually retiring types as known today.  

The only problem I ran into with ES 6 and monstache was related to the monstache documentation.  Some of the examples in the docs use curl commands that do not specify the `Content-Type` of the request.  I will need to update these examples to include that since ES 6 now requires it explicitly.  This does not affect the monstache program itself though, since requests my by the program currently include that header.    

Please let me know if you come across any issues, but based on my tests ES 6 works OK currently.
