### ISSUE TITLE
Make monstache reuse its stats indexes.

### ISSUE THREAD

**Issue by cmosgh** [rwynn/monstache#34]
I am having an issue with the way new instances of monstache after spawning will create new stats indexes.

I can already find lots of indexes created by monstache in ES

This is my config.toml file
```gzip = true
stats = true
index-stats = true
mongo-url = "mongodb://msdev456789112:27017"
elasticsearch-urls = ["http://elasticsearch:9200"]
elasticsearch-max-conns = 5
dropped-collections = true
dropped-databases = true
replay = false
resume = true
resume-write-unsafe = false
namespace-regex= "^(kf_dev456789112\\.(view\\-)+([A-Za-z\\-])+)"
namespace-exclude-regex = "none"
gtm-channel-size = 10
verbose = false
```

Is there any way to avoid the creation of multiple stats indexes or maybe clean them up automatically?

```yellow open monstache.stats.2017-12-09 Fe3JpzasRdGVg69J8C9XqA 5 1  5760    0   1.1mb   1.1mb
yellow open monstache.stats.2017-12-14 A_-kzbsASS-fswKFCRVlkg 5 1  5713    0   1.2mb   1.2mb
yellow open monstache.stats.2017-12-05 GppAM53DTXmuBejq0lvp1Q 5 1  5760    0   1.1mb   1.1mb
yellow open monstache.stats.2017-12-15 0MXNvqCkRkKaRm5xoxIdUQ 5 1  3950    0 870.4kb 870.4kb
yellow open monstache.stats.2017-12-04 dFO_ytsERs2LqBU8AcdF-w 5 1  3144    0 716.6kb 716.6kb
yellow open monstache.stats.2017-12-12 a8L1Rdd0RgOZU8B1ZehWXw 5 1  5760    0   1.1mb   1.1mb
yellow open monstache.stats.2017-12-10 TM4lXM5FTDibssgMjRdgMQ 5 1  5760    0   1.1mb   1.1mb
yellow open monstache.stats.2017-12-16 FfF64nRbSu-rP9PsIidzLQ 5 1  2880    0 641.7kb 641.7kb
yellow open monstache.stats.2017-12-11 onW3JJK9RNu7_J5ifjtlDw 5 1  5634    0   1.3mb   1.3mb
yellow open monstache.stats.2017-12-08 HQ5FUM9RSgaHlBRNh2cHYg 5 1  4294    0 954.7kb 954.7kb
yellow open monstache.stats.2017-12-18 9su5ctnDS_6prtkUWpMr-g 5 1  1546    0 804.8kb 804.8kb
yellow open monstache.stats.2017-12-06 sLwgJSesTKSC1B_JOL-33g 5 1  5413    0   1.2mb   1.2mb
yellow open monstache.stats.2017-12-17 tuqS6yjGRJuEar6D8iBP6g 5 1  2880    0 639.3kb 639.3kb
yellow open monstache.stats.2017-12-07 -9SaEmKNTDW9Lq_JkgWPYg 5 1  5146    0   1.1mb   1.1mb
yellow open monstache.stats.2017-12-13 c-Y0CzBtRK6IuG7nDDiVgQ 5 1  5760    0   1.1mb   1.1mb
```

**Comment by rwynn** [comment]
I’ve used curator to manage clean up of indexes with success. https://github.com/elastic/curator  

I think cleanup is maybe out of scope for monstache. Index per day is a pretty standard practice.

**Comment by rwynn** [comment]
I can make it possible that the date suffix is not added so that only 1 index is produced. But this is usually not how it’s done with logs since you usually want chunks such that you can delete old data without deleting current data.

**Comment by cmosgh** [comment]
I don't think is needed, thanks for the curator tip! 👍

**Comment by rwynn** [comment]
No problem.  I used index per day since logstash uses that same approach by default and tools like curator have support for managing indexes (e.g. deleting, closing) using an age filter.  The age filter can either pull the age from the index name or from the index metadata. 

I do think with a small change I can incorporate more flexibility by making the monstache stats index name pattern a configurable option.  I will do that under this issue so that in the future users will have more control.  

E.g. the default format will be `monstache.stats.2006-01-02` but if you just want index per month you can override to `monstache.stats.2006-01`.  Or leave out the date entirely if you just want 1 index.  

Thanks!
