### ISSUE TITLE
Official Elastic Go client

### ISSUE THREAD

**Issue by dblado** [rwynn/monstache#369]
Hi, just curious why monstache doesn't use the official elastic go client @ https://github.com/elastic/go-elasticsearch

**Comment by rwynn** [comment]
When I started monstache there weren't any official (company maintained) drivers for mongodb or elasticsearch.   

Eventually, the mongodb, inc driver was released.  At that time I already had many monstache releases on the community supported `mgo` driver.  The mgo driver was not getting lots of attention and I decided to bite the bullet and support the mongodb driver.  You can see that monstache supported it very soon after 1.0 if I remember correctly.  

I mention the mongodb driver only because I think it was a good decision to support the official driver.  It gets updated now all the time and the updates are important as that driver does quite a bit.  

On the other hand, I have a hard time finding a good reason to update the code to use the official Elasticsearch driver.  You can can see that Oliver's [driver](https://github.com/olivere/elastic/commit/e937d60d33acd506a5b58ea9fe2f995f42f66b7a) has been around for much longer than the [official](https://github.com/elastic/go-elasticsearch/commit/0a9ad88b300e64325718422757654db35a0cccfb). And honestly, monstache uses a fraction of the API, mostly just the _bulk part.  The official driver is more bare bones at this point if you look at the codebases.  

I will continue to re-evaluate over time but right now I don't see a compelling reason for a rewrite.

**Comment by dblado** [comment]
Thanks for the great explanation! Maybe add that to the docs for others.

**Comment by rwynn** [comment]
Thanks I will add to the docs.  

To clarify what I meant by "bare bones" when talking about the official elasticsearch go driver... it doesn't (yet) include what other language drivers (and Oliver's go driver) call the [bulk processor](https://github.com/olivere/elastic/wiki/BulkProcessor).  This is just usually some extra code that makes it very easy to invoke the bulk api, usually with support around having multiple threads, or in this case go routines, sending concurrent requests.  

The bulk processor is something that I would need to reproduce since it's not already in the official driver.  Though it might be a good opportunity for some performance optimizations to write my own, I think Oliver's is already pretty good.
