### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bigbigword3** [rwynn/monstache#381]
after full-sync ,then throw:
ERROR 2020/06/08 11:28:37 (Unauthorized) not authorized on admin to execute command { serverStatus: 1, lsid: { id: UUID("xxxxxx-deea-415f-bdc0-9e48d20be633") }, $clusterTime: { clusterTime: Timestamp(1591586916, 8), signature: { hash: BinData(0, DFD7C29BC0645AFAEB52C13F3F28CD1EB1F81FF8), keyId: 4834831979272203385 } }, $db: "admin" }

can you help?

**Comment by bigbigword3** [comment]
why need admin-db write permission?

**Comment by rwynn** [comment]
The command that is failing is a read command.  It is executing [serverStatus](https://docs.mongodb.com/manual/reference/command/serverStatus/) to get the timestamp value from the server.  It is only doing this because `resume` is true and when this is the case it will try to save the timestamp after sync is complete.  You can turn off resume.  If you need resume then you would need to allow running `serverStatus` command for the user.  The error is not fatal, it just means that you would potentially not have the timestamp to resume from at a later time.

**Comment by bigbigword3** [comment]
it works! thanks
