### ISSUE TITLE
Create index I want to modify properties how to do

### ISSUE THREAD

**Issue by codexuexi** [rwynn/monstache#389]
Add parameters
```
{
  "properties": {
    "t": {
      "type": "text",
      "analyzer": "ik_max_word",
      "search_analyzer": "ik_smart"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/28785644/85203070-9b69ca80-b33d-11ea-9f32-f74a91032e61.png)

I need to use a tokenizer

[ik](https://github.com/medcl/elasticsearch-analysis-ik)

I don't know how to set up mapiing

**Comment by codexuexi** [comment]
I haven't done it yet, please help me

**Comment by rwynn** [comment]
Hi @codexuexi one solution to set up the mapping is to use [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html).  You will need to setup the index template according to the Elasticsearch docs **before** running monstache.  Then when monstache sends the data to the index your mappings will be used instead of the default mappings.  You may have to delete your existing indexes in Elasticsearch and do a full synch after you have created the templates.  Hope this helps.

**Comment by codexuexi** [comment]
> Hi @codexuexi one solution to set up the mapping is to use [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html). You will need to setup the index template according to the Elasticsearch docs **before** running monstache. Then when monstache sends the data to the index your mappings will be used instead of the default mappings. You may have to delete your existing indexes in Elasticsearch and do a full synch after you have created the templates. Hope this helps.

Thank you, this works
