### ISSUE TITLE
Does it/Will it support parent joins?

### ISSUE THREAD

**Issue by aguyinmontreal** [rwynn/monstache#43]
Hi there!

Does this project or Will this project support the new [parent joins](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html) (in replacement of child/parent relationships)?

Thank you!

**Comment by rwynn** [comment]
Hi, I don't see a reason yet why it wouldn't already support this (with some work on your part).  Monstache will not create the index mapping that contains the join field.  You would need to do that yourself upfront before indexing.  Then after that join field is in place you would need a Javascript or Golang plugin to alter the source document appropriately to include that join field AND ensure that routing is set such that parents and children are routed to the same shard.

See https://rwynn.github.io/monstache-site/advanced/#middleware and https://rwynn.github.io/monstache-site/advanced/#routing

**Comment by aguyinmontreal** [comment]
Thank you! I'll give it a try!

**Comment by aguyinmontreal** [comment]
Sorry to bother, but my "parent" documents and my "child" documents are in two different MongoDB collections.

Can Monstache bring them both under the same namespace (i.e. both index and type) without conflicts?

Thank you

**Comment by rwynn** [comment]
@aguyinmontreal I've just added some docs around this at https://rwynn.github.io/monstache-site/advanced/#joins

To do what you want to accomplish you would have 2 mapping functions in your TOML config file.  One for each collection.  Then on the _meta_monstache attribute, in addition to a `routing` property set the `index` and `type` properties to what you want.  You will be overriding the defaults where index is `${db}.${collection}` and type is `${collection}`.

**Comment by rwynn** [comment]
This link shows more about overriding the index and type.  https://rwynn.github.io/monstache-site/advanced/#indexing-metadata

**Comment by aguyinmontreal** [comment]
And it will not conflict on stateful resume?

**Comment by rwynn** [comment]
The only conflict I can think of when you merge 2 collections into 1 index like this is if document ids collide across those collections.  MongoDB only ensures that _id is unique within a single collection. So it's possible, though unlikely if you are using auto-generated _ids, that they can collide and write to the same document in the converged target Elasticsearch index.  

I don't think there is any problem with resuming related to this.  What case are you thinking about?  The stateful resume only saves timestamps of processing documents. When resuming it begins tailing after the last processed timestamp instead of fast-forwarding to the end of the oplog.  You will notice if you don't replay, then it starts tailing from the end.  If you replay it starts tailing from the beginning.  If you resume it starts processing from the last timestamp it has saved. But regardless of where it starts, it always evaluates these functions before indexing.  

You will notice that when you do custom routing like this you get additional documents in MongoDB in the collections `monstache.meta`.  These documents are there so that if you perform a delete in MongoDB the routing attribute is set correctly on the delete request to Elasticsearch.  Monstache only needs to preserve the routing information on deletes when the default routing is overridden.  The default is to routing by Elasticsearch _id (which is done by Elasticsearch automatically).

**Comment by aguyinmontreal** [comment]
Alright!

I just wanted to double-check before I start importing all my mongo-connector stuff to Monstache!

Thank you so much for your guidance!

**Comment by rwynn** [comment]
@aguyinmontreal let me know how your transition to Monstache ends up going.  I'm very interested in any gaps that exist between it and other solutions.

**Comment by aguyinmontreal** [comment]
@rwynn Small comment, if I may.
I noticed you use "test.test" as the example Elasticsearch namespace.

Elasticsearch recommends that we name every types as "_doc" from now on. (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/removal-of-types.html#_schedule_for_removal_of_mapping_types))

so it should be "test._doc", I guess.  (Does Monstache allow types starting with "_"?  I know mongo-connector doesn't.)

**Comment by rwynn** [comment]
You can name the index and type whatever you want them to be. I don’t think monstache imposes restictions other than https://github.com/elastic/elasticsearch/issues/6736

**Comment by rwynn** [comment]
So actually no monstache would not allow type to be _doc because it used to be a rule that type could not start with underscore and monstache is still following.

**Comment by aguyinmontreal** [comment]
Would you consider allowing it?

**Comment by rwynn** [comment]
Yeah I’ll take a look at it. I may just remove the code that checks any of this and just let ES determine what is valid and not. 

You can actually use _doc as the type if you set it from the javascript function. I think that is a “bug” that works in your favor here.

**Comment by rwynn** [comment]
@aguyinmontreal this should be fixed now and the docs updated.  Use the 4.0.0 release.  Thanks and let me know if you run into any problems.

**Comment by aguyinmontreal** [comment]
@rwynn Alright!  I'll take a look at it!  

So the default index name for Elastic 6.2+ becomes "mongodb database name . mongodb collection name"?  So the full namespace (index + type) becomes "mongodb database name . mongodb collection name . _doc"?

Are you sure two dots in the namespace are allowed?

**Comment by rwynn** [comment]
ES index is ‘db.collection’ and I’ve used dots with no problem.  I don’t think elasticsearch has namespace just index and type.  Type is _doc.

**Comment by aguyinmontreal** [comment]
Sorry for the confusion.  

For me: 
1- index + type equals namespace
2-index is the part before the dot
3-type is the part after the doc

**Comment by rwynn** [comment]
An index can contain a dot. The whole thing is the index. You can try it.

**Comment by aguyinmontreal** [comment]
Hi rwynn!

I saw this note here in the docs, and I'm a little confused:

![image](https://user-images.githubusercontent.com/19701656/36346584-99dc2350-140e-11e8-95c0-f39ae38b637e.png)

In my case, as we discussed, my parent and my child documents are not coming from the same namespace. So even if I can prefix the dynamic index of either the parent or the child, the remaining one will be prefixed with the wrong namespace.

What is best to do?

**Comment by rwynn** [comment]
You probably don’t need to worry too much about that comment. There is a feature that monstache deletes the index when the collection or db is dropped.  You will just need to do that delete index manually. Drop collections and db not too common event. 

The ObjectId are converted to string before your function and is called.
