### ISSUE TITLE
Can I use dbname as the name of index

### ISSUE THREAD

**Issue by snoopy83101** [rwynn/monstache#49]
now, my index name is
"geek001.db1"   

In the past, I was using mongo-connector. 
name is "geek001"

So the programs are all querying this

“/geek001/db1/_search.......”

Can I still do this right now?

**Comment by rwynn** [comment]
You can use a mapping. From the docs...

[[mapping]]
namespace = "geek001.db1"
index = "geek001"
type = "db1"

But I don’t recommend that generally. There is a reason it is done differently than mongo connector. Specially I don’t believe that all mongo collections in a db should map to a single elasticsearch index - most importantly because _id is not guaranteed unique across mongo collections. 

If you know what you are doing and understand the risks then it’s OK.

**Comment by rwynn** [comment]
Index names are now lowercased in monstache.
