### ISSUE TITLE
<< Handling Interface failures - Production >>

### ISSUE THREAD

**Issue by pcinnusamy** [rwynn/monstache#496]
@rwynn ,

How does monstache handle failure / retries if ES is unavailable while we restart the cluster?

Could you please confirm whether Monstache service will be resumed automatically when ES cluster is up.

**Comment by rwynn** [comment]
hi @pcinnusamy , 

when monstache is first started if the elasticsearch health check does not pass within the configured [timeout](https://rwynn.github.io/monstache-site/config/#elasticsearch-healthcheck-timeout-startup) then monstache will exit and need to be restarted. 

once this initial healthcheck passes monstache will continue to retry requests if they fail due to network errors.  In this case you would see error messages along the lines of "elastic: bulk processor monstache was unable to perform work: _error message_".  Monstache will [wait and try again](https://github.com/olivere/elastic/blob/233b88339beb38d5634ef7f8a5e2c7fe29084a63/bulk_processor.go#L508) if this is due to a network error.

**Comment by pcinnusamy** [comment]
Thanks for your detailed explanation @rwynn
