### ISSUE TITLE
Question on duplication

### ISSUE THREAD

**Issue by Crispy1975** [rwynn/monstache#5]
Just started testing with monstache and so far very impressed. I have a quick question regarding duplicates; specifically how are MongoDB `_id` properties mapped to ElasticSearch, and how when a document in MongoDB is updated is the correct ElasticSearch document updated?

**Comment by rwynn** [comment]
The default mapping is as follows:
```
mongodb database -> elasticsearch index
mongodb collection -> elasticsearch type
mongodb document _id -> elasticsearch document id
```
Any operation on a mongo document (insert, update, delete) will be recorded in the oplog with it's _id and that will eventually be propagated into a bulk index command to ES where the id is specified as the _id in mongodb.

So I think you may be correct above the potential for collisions since mongo _ids are unique at the collection level (not guaranteed across the database) while ES ids must be unique at the index level.  

According to [link](http://stackoverflow.com/questions/5303869/mongodb-are-mongoids-unique-across-collections), duplicate _ids across the database are unlikely with autogenerated _ids.

Regardless, I should change the default mapping such that 

```
elasticsearch index <- mongodb database . mongodb collection
```

Thanks for giving monstache a try and reporting this issue.

**Comment by Crispy1975** [comment]
Awesome, thanks. :+1:
