### ISSUE TITLE
Fielddata error when searching the index

### ISSUE THREAD

**Issue by kgrvamsi** [rwynn/monstache#52]
We started updating the data from the mongodb to Elasticsearch with Monstache and updating the looks fine and when i started to fetch the data as per the https://olivere.github.io/elastic/ golang library i see the following issue

![image](https://user-images.githubusercontent.com/1199031/37446417-d828ebb2-27ea-11e8-9b20-41cd1f56902d.png)

Current data that Monstache created
![image](https://user-images.githubusercontent.com/1199031/37446334-6d76dfcc-27ea-11e8-9558-8319f15e448a.png)

Example Index data with Fielddata 

![image](https://user-images.githubusercontent.com/1199031/37446318-552c7eb8-27ea-11e8-94e1-18244a249ad3.png)

@rwynn Is there a way to make certain data enabled with fielddata or is there any alternative solution for this issue?

Query used with the library
```
hostquery := elastic.NewBoolQuery().Must(elastic.NewTermQuery("last_updated", date))
	res, err := eclient.Search().
		Index("testing.inventoryhosts").
		Type("InventoryHosts").
		Query(hostquery).
		From(0).Size(6000).
		Pretty(true).
		Sort("last_updated", true).
		Do(ctx)
	if err != nil {
		return nil, err
	}
```

**Comment by rwynn** [comment]
There is not any way to set explicit mapping information with monstache. It just sends the data and if there is any existing mapping for the index it will be used. Otherwise, elasticsearch will make a guess as to what the type should be for the data. So you can solve this by explicitly mapping the fields for your indexes, either per index or with an index template, once, before running monstache. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by rwynn** [comment]
Also I think you want the **date** type for last updated and not **text** at all. Not sure why it is not being auto mapped as a date. But you can configure that explicitly.

**Comment by kgrvamsi** [comment]
@rwynn thanks for the info but i was checking the ES docs as well and it says that the query for text fields happens from in memory and use lot of jvm heap sapace.

Reference url:
https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html
``
Instead, text fields use a query-time in-memory data structure called fielddata. This data structure is built on demand the first time that a field is used for aggregations, sorting, or in a script. It is built by reading the entire inverted index for each segment from disk, inverting the term ↔︎ document relationship, and storing the result in memory, in the JVM heap.
``

I'm still trying to understand how can we retrieve the rows from the index with the text field or any thing else.(confused)

**Comment by rwynn** [comment]
@kgrvamsi I was not recommending using a text field for `last_updated` but rather to make it a date type field.  

Let me try to explain.  You should start by deleting any current indexes you have since the type information cannot be modified once it's set.  

First you should take your data and think about a data mapping using the types available in Elasticsearch.  Then you should pre-create the indexes that monstache will write to and when you create the indexes supply a mapping for each field in the type.  E.g. in this case I think you will want `last_updated` to be a ***date*** type.  

To explain a little bit about why Elasticsearch is complaining in the first place.  The mapping that was automatically produced for `last_updated` was a `multi-field`: text and keyword.  

https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html

Elasticsearch mapped last_updated as a text field and also as a keyword field as `last_updated.keyword`.  `last_updated.keyword` is the field name that you can use in a term query, sorting, and aggregations.  

For example, I think something like this should work without the error

```
hostquery := elastic.NewBoolQuery().Must(elastic.NewTermQuery("last_updated.keyword", date))
	res, err := eclient.Search().
		Index("testing.inventoryhosts").
		Type("InventoryHosts").
		Query(hostquery).
		From(0).Size(6000).
		Pretty(true).
		Sort("last_updated.keyword", true).
		Do(ctx)
	if err != nil {
		return nil, err
	}
```

Notice that when you are doing term query and sorting you want to use the keyword typed version of the field `last_updated.keyword` not the text typed `last_updated`.  

That is why in the docs it says: It is often useful to index the same field in different ways for different purposes. This is the purpose of multi-fields. For instance, a string field could be mapped as a text field for full-text search, ***and as a keyword field for sorting or aggregations***.

You would use `last_updated` in this example when you are doing full text search.  That is the reason Elasticsearch is indexing the same field 2 ways.  To understand the difference read...

https://www.elastic.co/guide/en/elasticsearch/guide/current/term-vs-full-text.html

All this explanation aside, I think you still want to make sure last_updated is mapped as a proper date field since as a text or keyword field you would only be able to match it exactly and not perform date oriented comparisons.  And to do this you would need to delete and set mappings on your indexes before re-indexing.

**Comment by rwynn** [comment]
To check why your data for the field was not automatically mapped as a date, read these docs:

https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#date-detection

**Comment by rwynn** [comment]
The main issue with your query was the sort on a text field instead of a sort on the keyword sub-field.

**Comment by rwynn** [comment]
By the way, monstache will produce a valid date format that Elasticsearch recognizes when you use the `Date` object in MongoDB.  

```
rs1:PRIMARY> db.test.insert({foo: 1, bar: new Date()});
WriteResult({ "nInserted" : 1 })
```
```
TRACE 2018/03/15 19:55:05 POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/6.1.9 (linux-amd64)
Content-Length: 180
Accept: application/json
Content-Type: application/x-ndjson
Accept-Encoding: gzip

{"index":{"_index":"test.test","_id":"5aaacf98f49e05e4d939a086","_type":"_doc","version":6533262461196304386,"version_type":"external"}}
{"bar":"2018-03-15T19:55:04.315Z","foo":1}

TRACE 2018/03/15 19:55:06 HTTP/1.1 200 OK
Content-Length: 260
Content-Type: application/json; charset=UTF-8

{"took":1144,"errors":false,"items":[{"index":{"_index":"test.test","_type":"_doc","_id":"5aaacf98f49e05e4d939a086","_version":6533262461196304386,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
```
```
curl localhost:9200/test.test/_mapping?pretty
{
  "test.test" : {
    "mappings" : {
      "_doc" : {
        "properties" : {
          "bar" : {
            "type" : "date"
          },
          "foo" : {
            "type" : "long"
          }
        }
      }
    }
  }
}


```

See how the date was sent to Elasticsearch in a format it recognized and automatically mapped to a date?  So, I would recommend either storing your date using the MongoDB date object OR worst case storing the date as a string in MongoDB in the format above (e.g `2018-03-15T19:55:04.315Z`) since Elasticsearch will then automatically map the type correctly.

If changing the format of your MongoDB data is not possible look into adding your format using the following instructions:

https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#_customising_detected_date_formats

**Comment by kgrvamsi** [comment]
@rwynn thanks for the info and i'm trying to make the changes to the db as we made this field string but not into date format.
