### ISSUE TITLE
Setting `enable-http-server = true` in config.toml is not working

### ISSUE THREAD

**Issue by a-magdy** [rwynn/monstache#58]
Hi @rwynn,

Thank you for your great work in this tool, really useful :) 👍

I noticed that using `enable-http-server = true` only in `config.toml` doesn't start the server, I had to add it to the attribute to the command like: `--enable-http-server -f /monstache/config.toml`

I tested it in different docker images, `rwynn/monstache:4.3.2.cgo`, `4.3.1` & `4.3.2` and I got the same result: "I have to use the attribute --enable-http-server"

Thanks

**Comment by rwynn** [comment]
Hi @a-magdy can you please try moving `enable-http-server = true` as the first line of your toml config file?  As well as any other simple config settings that you might have.  

I think there is a bug in the toml parser where if you have definitions below a TOML table, e.g. a [[script]] then the parser thinks that lines below that belong to the table instead of at the global level.  

So for example
```
# start with simple values
enable-http-server = true

# put all tables at the end
[[script]]
namespace = "mydb.mycollection"
...
``` 
instead of 
```
[[script]]
namespace = "mydb.mycollection"
...

enable-http-server = true
```
This may not be the problem but that's a guess.  I just tried a simple config and it worked ok for me.  So maybe that is the problem?

**Comment by a-magdy** [comment]
Hi @rwynn 

Thanks for the detailed answer, you are right, I removed the attribute from the command and moved the enable-http-server above tables in the config.toml file, and it worked :D 

![28cj0g](https://user-images.githubusercontent.com/14139855/38760542-311fc5da-3f7c-11e8-94ff-3ab7ef27d184.jpg)

cheers :)
