### ISSUE TITLE
Race condition between data syncing and data reading

### ISSUE THREAD

**Issue by lgmf** [rwynn/monstache#620]
Hi

I'm using Monstache to sync data from MongoDB on ou Opensearch.

Syncing data takes some time to be completed and sometimes the front-end receives outdated information.

I know that the problem is not on Monstache but I wonder if someone had to deal with that

Thank you

**Comment by lgmf** [comment]
@rwynn 

Reading the docs I've seen this
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html#_examples_14

![image](https://user-images.githubusercontent.com/8532045/176505482-48c3919f-82eb-42b5-a69a-868e0d20eefb.png)

Is there a way to configure this behavior on Monstache?

**Comment by rwynn** [comment]
@lgmf I can look into adding a config for that.  I think the global refresh is or at least used to 1s by default for Elasticsearch.  

Have you configured this to be 1 second?
https://rwynn.github.io/monstache-site/config/#elasticsearch-max-seconds

It defaults to 1s but changes to default to 5s if you enable direct reads.  If you explicitly set it, it doesn't change the value regardless of whether or not direct reads are enabled.

**Comment by lgmf** [comment]
Thanks for the answer.

I'll try it now.

By the way, do you believe there are other options that may fine-tune our syncing process?

The problem I'm trying to solve is:

1 - The client updates/creates/deletes a record
2 - The action is persisted on MongoDB and the API returns 200
3 - The client makes a request to update a DataTable
4 - The search API returns outdated data

I believe that the problem is that the client's request is being faster than the syncing process

**Comment by rwynn** [comment]
you need the write to MongoDB to not return until the document is synced to Elastic for your use case.  But I don't think this is possible at the moment because monstache works asynchronously reading the change events.  Even if Elastic made the document available in search the instant monstache sent it, you would still have a gap in time.  I think the best way to describe this is https://en.wikipedia.org/wiki/Optimistic_replication.  The only thing you can do it try to minimize the lag.

another option to try is to set `elasticsearch-max-docs` to `1`.  That is not good for throughput but decreases the latency.

**Comment by lgmf** [comment]
Thanks a lot for your help!
