### ISSUE TITLE
Mongodb (Update) -> Elasticsearch (Insert)

### ISSUE THREAD

**Issue by Gittekken** [rwynn/monstache#80]
The way I have my Mongodb setup is to mainly update the docs within the database. Because of this Monstache will update the existing Elasticsearch’s data as well. How can I instead have Monstache insert the updated Mongodb data into Elasticsearch?

Thanks 
Ken

**Comment by rwynn** [comment]
The closest thing Monstache has to what you describe is https://rwynn.github.io/monstache-site/config/#time-machine-namespaces.  

I would consider allowing the ability to override the _id of the document sent to Elasticsearch in a future version.   This would allow one to empty the _id so that each event generates a new document in Elasticsearch.

**Comment by Gittekken** [comment]
no problem I ended up creating a dedicated collection for insertions using changestreams.
