### ISSUE TITLE
Referencing other documents for routing

### ISSUE THREAD

**Issue by deepanuchiha** [rwynn/monstache#86]
Hi,
I'm trying to use monstache to sync ES and MongoDB. I've created indexes based on the data.
For example, I have two collections namely fruits and states. I want to sync fruits collection to ES.
**fruits collection** {
name: "apple",
state: "alabama" 
}
**states collection** {
name: "alabama",
country: "United States"
}

Now I've created indexes in ES with Country names. I want to get the country name by querying in the states collection for the given state while routing inside the script in config.toml file. Is that possible?

**Comment by rwynn** [comment]
yes, it should be possible.

```
[[script]]
namespace = "test.fruits"
script = """
module.exports = function(fruit) {
   fruit.country = findOne({name: fruit.state}, {database: "test", collection: "states"}).country;
   return fruit;
}
"""
```

**Comment by deepanuchiha** [comment]
Thanks a ton for the quick response :)
It's working like a charm. I better take a good look at the documentation. :+1:

**Comment by zvictor** [comment]
Hi @rwynn,

Thank you for your great work in this tool! beautifully done 👌
I have a question and I will use this issue here as base for my post because I believe the question raises naturally from the solution you proposed above.

If I am fetching `country` from another collection and storing it inside `fruit` whenever there is an insert or update in the `fruit` doc, **how can I keep all the `country` fields updated also when changes happen in the `states` collection**?

I tried doing a couple of things, and the closest I got can be seen below, but it gives me duplicates instead of updates:

```toml
[[script]]
namespace = "test.a-complex-aggregated-view"
routing = true
script = """
module.exports = function(doc) {
  var fruit = findOne(
    {
      _id: doc.fruit._id,
    },
    {
      database: 'test',
      collection: 'fruits',
    }
  )

  fruit._meta_monstache = { index: 'fruits', routing: fruit._id }
  fruit.country = doc.country

  return fruit
}
"""
```

**Comment by rwynn** [comment]
@zvictor Thanks, I hope you’re finding this to be useful. Sorry I’ve been busy lately and didn’t get a chance to respond. I will think about this a bit more when I get a some free time but I’m not sure monstache is currently designed to handle your use case well. 

One reason is that monstache is designed such that the document _id cannot be overridden in a script. The _id that’s passed to Elasticsearch is the _id of the original Mongo doc; even if you replace the _id or return a new object with a new _id the original will still be used. That is probably why you are seeing duplicates. 

Also once you embed an object from another collection, the only way to keep in sync using monstache would be to reindex by restarting direct reads so that the country is updated by fetching it again in the script phase.
