### ISSUE TITLE
Eating too much memory

### ISSUE THREAD

**Issue by Pylipala** [rwynn/monstache#90]
It eats up to 1.65 GB on my 4GB server
```
PID    USER   PR  NI   VIRT          RES       SHR  S   %CPU   %MEM     TIME+    COMMAND
9817  root      20   0   2962624 1.650g   2800 S   4.6       45.0          0:17.15    monstache
```
As far as I can see, a syncing program should not eat so much memory. 
Is it normal? How much memory it takes on your machine?

**Comment by rwynn** [comment]
You can also set direct-read-split-max to 1 to further reduce memory usage.

**Comment by Pylipala** [comment]
You are right, I should have run into error loop. It keeps printing 
```
ERROR 2018/07/30 12:29:06 elastic: bulk processor "monstache" failed: json: unsupported value: NaN
ERROR 2018/07/30 12:29:06 Bulk index request with execution ID 894 failed: json: unsupported value: NaN
ERROR 2018/07/30 12:29:06 elastic: bulk processor "monstache" failed: json: unsupported value: NaN
```
Thanks for your quick response. I will see if I could use some transformation to make it work.

**Comment by Pylipala** [comment]
You are right. Field `_doc._source.Stats.Workers.Queued` of `monstache.stats.2018-07-30` index is growing bigger and bigger.
![image](https://user-images.githubusercontent.com/1218075/43403155-0054a7ac-9447-11e8-89f6-f05fc035659e.png)

**Comment by Pylipala** [comment]
I was using a docker built 3 weeks ago. Then I upgraded it today to a version built 3 days ago. The problem still exists.

**Comment by rwynn** [comment]
You can probably get rid of a lot of the errors by setting the `prune-invalid-json` config to true.  That will help to move the documents out being queued in memory and into Elasticsearch.

https://rwynn.github.io/monstache-site/config/#prune-invalid-json

I also added a commit to the elastic client a few weeks back that should prevent these items with JSON serialization errors from being queued (since they will never get 'fixed').  

https://github.com/olivere/elastic/pull/802

This PR should be preventing those NaN errors from contributing to the queue in the driver.   I'm not sure if this was applied to versions of the client prior to Elasticsearch 6.  It looks like it was at least merged into olivere:release-branch.v6.  Are you using monstache (for ES6+) or monstache.v3 for (ES5-)?

Regardless, `prune-invalid-json` should remove the individual fields that cannot be converted to JSON before even submitting to the driver.     

Also, since you have a lot of collections to sync I would recommend setting the `direct-read-split-max` to 1 and also `elasticsearch-max-bytes` to 2000000.  That should keep the memory lower.  The defaults for those are 9 and 8MB in bytes.   

Each MongoDB collection is split and all splits are read concurrently.  So if you have 31 collections with a max split of 1, then you would still have 62 connections to MongoDB reading those collections concurrently.   The default max split is 9, so with 31 collections that would result 310 connections to MongoDB.  

Then on the other side of the pipe you have `elasticsearch-max-conns` go routines (http workers).  These each wait to fill up to `elasticsearch-max-bytes` before flushing a bulk request.  The defaults for these values are 4 conns (go routines) with 8MB max built up before each with flush.  You can turn down `elasticsearch-max-conns` to 2.

**Comment by rwynn** [comment]
It appears that my PR was only applied to the Elasticsearch v6 client and not the v5 client.  

https://github.com/olivere/elastic/blob/release-branch.v5/bulk_processor.go

You will see from that code that the request is added regardless of whether or not it will eventually error out in the transform to JSON.

https://github.com/olivere/elastic/blob/release-branch.v5/bulk_processor.go#L454

**Comment by rwynn** [comment]
So all together I would recommend that for your use case you try with

```
prune-invalid-json = true
direct-read-split-max = 1
elasticsearch-max-bytes = 2000000
elasticsearch-max-conns = 2
```
Please let me know if that helps with the number queued in the stats and the memory usage.

**Comment by Pylipala** [comment]
Yes it works, memory usage is limited to 250MB now. 

Thank you very much.

My monstache version is below:
```
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
rwynn/monstache                                 latest              8a6edb5bf647        4 days ago          19.2MB
```

**Comment by Pylipala** [comment]
You are right. Field `_doc._source.Stats.Workers.Queued` of `monstache.stats.2018-07-30` index is growing bigger and bigger.
![image](https://user-images.githubusercontent.com/1218075/43403155-0054a7ac-9447-11e8-89f6-f05fc035659e.png)
